let filmyYtLinki = [
['https://www.youtube.com/embed/naq9D6jvnhA', ['film-podstawa2', 'film-rozszerzenie2'], 'Matematyka - Wielomiany jednej zmiennej (część I)', '8', 'youtube'],
['https://www.youtube.com/embed/ev_-R-3W_yo', ['film-podstawa2', 'film-rozszerzenie2'], 'Co to jest wielomian? #1 [ Wielomiany ]', '8', 'youtube'],
['https://www.youtube.com/embed/V2D8wYNpAk8', ['film-podstawa2', 'film-rozszerzenie2'], 'Dodawanie i odejmowanie wielomianów', '8', 'youtube'],
['https://www.youtube.com/embed/VZA09ymFcV4', ['film-podstawa2', 'film-rozszerzenie2'], 'Szybko i na temat. Dzielenie Wielomianów Krok po Kroku', '8', 'youtube'],
['https://www.youtube.com/embed/77CgfPFONWE', ['film-podstawa2', 'film-rozszerzenie2'], 'Sprawdzian na 5!WIELOMIANY (rozkład na czynniki, dzielenie, Horner, równania, TW o reszcie/Bézouta)', '8', 'youtube'],
['https://www.youtube.com/embed/KLjji_I3XvA', ['film-podstawa2', 'film-rozszerzenie2'], 'Liceum. Klasa II. Wielomiany. Nierówności wielomianowe', '8', 'youtube'],
['https://www.youtube.com/embed/vQgrdSAjYaE', ['film-podstawa2', 'film-rozszerzenie2'], 'Dodawanie, odejmowanie i mnożenie wielomianów #3 [ Wielomiany ]', '8', 'youtube'],
['https://www.youtube.com/embed/f_Kv7-oiMLw', ['film-podstawa2', 'film-rozszerzenie2'], 'WSZYSTKO o: NIERÓWNOŚCI WIELOMIANOWE. Jak rysować wykres wielomianu?Co to jest krotność pierwiastka?', '8', 'youtube'],
['https://www.youtube.com/embed/5UaDP_fF8hY', ['film-rozszerzenie2'], 'Wielomiany co trzeba ogarniać? Matura Matematyka Rozszerzenie', '8', 'youtube'],
['https://www.youtube.com/embed/eQTEXfqLQYE', ['film-podstawa2', 'film-rozszerzenie2'], 'Wzory skróconego mnożenia - sześcian sumy i różnicy.', '8', 'youtube'],
['https://www.youtube.com/embed/ehRXj3GEpIw', ['film-rozszerzenie2'], 'Matura rozszerzona - kurs - wzory skróconego mnożenia', '8', 'youtube'],
['https://www.youtube.com/embed/Q-lkLAeKtlA', ['film-podstawa2', 'film-rozszerzenie2'], 'Jak dzielić (pisemnie) WIELOMIAN przez DWUMIAN na MATURZE PODSTAWOWEJ?', '8', 'youtube'],
['https://www.youtube.com/embed/9piOqP5jcw4', ['film-podstawa2', 'film-rozszerzenie2'], 'Dzielenie wielomianów #4 [ Wielomiany ]', '8', 'youtube'],
['https://www.youtube.com/embed/msfZ8_eHIoM', ['film-podstawa2', 'film-rozszerzenie2'], 'Pierwiastki całkowite oraz wymierne wielomianu #8 [ Wielomiany ]', '8', 'youtube'],
['https://www.youtube.com/embed/5ywgT7USp4Y', ['film-rozszerzenie2'], 'Wielomiany na poziomie rozszerzonym', '8', 'youtube'],
['https://www.youtube.com/embed/KPOFrG8HOwo', ['film-podstawa2', 'film-rozszerzenie2'], 'WEKTOR w układzie współrzędnych', '1', 'youtube'],
['https://www.youtube.com/embed/LqBrQp-f2I0', ['film-podstawa2', 'film-rozszerzenie2'], 'Wektory - Wprowadzenie Odc.1 (na szybko bo wychodzę za 5 min)', '1', 'youtube'],
['https://www.youtube.com/embed/WCOChZ-BaCM', ['film-rozszerzenie2'], 'Wektory - wprowadzenie - najważniejsze informacje', '1', 'youtube'],
['https://www.youtube.com/embed/9agT9Lu6pJQ', ['film-podstawa2', 'film-rozszerzenie2'], 'Liceum. Klasa I. Wektor w układzie współrzędnych', '1', 'youtube'],
['https://www.youtube.com/embed/C3RlRjnBE0c', ['film-podstawa2', 'film-rozszerzenie2'], 'Przesuwanie wykresów funkcji wzdłuż osi X i Y oraz o wektor', '1', 'youtube'],
['https://www.youtube.com/embed/sD4mC5Ux6pM', ['film-podstawa2', 'film-rozszerzenie2'], 'Przesuwanie wykresu funkcji wzdłuż osi OX i OY', '1', 'youtube'],
['https://www.youtube.com/embed/7xxIkATsBeo', ['film-podstawa2', 'film-rozszerzenie2'], 'Przesunięcie wykresu funkcji wzdłuż osi układu współrzędnych cz.2 MATEMATYKA LEKCJE Z FSORE', '1', 'youtube'],
['https://www.youtube.com/embed/nxuZvjTxMOk', ['film-podstawa2', 'film-rozszerzenie2'], 'Matematyka - Przesunięcie funkcji wzdłuż osi OX', '1', 'youtube'],
['https://www.youtube.com/embed/WMVe1NZBrsE', ['film-podstawa2', 'film-rozszerzenie2'], 'Przesuwanie funkcji w górę, w dół, w prawo, w lewo | MatFiz24.PL', '1', 'youtube'],
['https://www.youtube.com/embed/yLRIkacEAy0', ['film-podstawa2', 'film-rozszerzenie2'], 'Przekształcanie wykresu funkcji - symetria względem osi OX i OY', '1', 'youtube'],
['https://www.youtube.com/embed/Q-0ylc-dqn8', ['film-podstawa2', 'film-rozszerzenie2'], 'Symetria osiowa względem osi OX i OY - definicje, przykłady', '1', 'youtube'],
['https://www.youtube.com/embed/m48o2yHJoDA', ['film-podstawa2', 'film-rozszerzenie2'], 'Symetria osiowa w układzie współrzędnych #3 [ Symetria ]', '1', 'youtube'],
['https://www.youtube.com/embed/H9i1y9Hdtl4', ['film-podstawa2', 'film-rozszerzenie2'], 'Liceum. Klasa I. Symetria środkowa i osiowa w układzie współrzędnych', '1', 'youtube'],
['https://www.youtube.com/embed/dPZVFCuQCvI', ['film-podstawa2', 'film-rozszerzenie2'], 'Symetria środkowa. Symetria środkowa względem punktu (0,0) - definicje, przykłady', '1', 'youtube'],
['https://www.youtube.com/embed/qCqHk3kFGZo', ['film-podstawa2', 'film-rozszerzenie2'], 'Symetria środkowa względem punktu 0(0,0)', '1', 'youtube'],
['https://www.youtube.com/embed/4S0vLLSkcBs', ['film-podstawa2', 'film-rozszerzenie2'], 'Symetria środkowa w układzie współrzędnych #6 [ Symetria ]', '1', 'youtube'],
['https://www.youtube.com/embed/uMRFEP8yQTg', ['film-rozszerzenie2'], 'Własności wartości bezwzględnej LEKCJE Z FSOREM #82 ROZSZERZENIE', '2', 'youtube', ['Własności wartości bezwzględnej']],
['https://www.youtube.com/embed/ByV7VITIEzA', ['film-rozszerzenie2'], 'Matematyka - Własności wartości bezwzględnej', '2', 'youtube', ['Własności wartości bezwzględnej']],
['https://www.youtube.com/embed/R3um24WEGvU', ['film-rozszerzenie2'], 'Wartość bezwzględna na ROZSZERZENIU: Równania i nierówności z JEDNYM modułem', '2', 'youtube', ['Równania z wartością bezwzględną', 'Nierówności z wartością bezwzględną']],
['https://www.youtube.com/embed/JWYCRqjReDo', ['film-rozszerzenie2'], 'Wartość bezwzględna na ROZSZERZENIU: Równania i nierówności z DWOMA modułami', '2', 'youtube', ['Równania z wartością bezwzględną', 'Nierówności z wartością bezwzględną']],
['https://www.youtube.com/embed/SvhWh9DeHI4', ['film-podstawa1', 'film-rozszerzenie1'], 'Działania na zbiorach', '1', 'youtube', ['Zbiór. Działania na zbiorach']],
['https://www.youtube.com/embed/Z7qMR5ay8Zg', ['film-podstawa1', 'film-rozszerzenie1'], 'Szybko i na temat. Zbiory + Zadania.', '1', 'youtube', ['Zbiór. Działania na wzorach']],
['https://www.youtube.com/embed/g0Rk_OTvb_o', ['film-podstawa1'], 'ZBIORY LICZBOWE I OŚ LICZBOWA - wszystko co musisz wiedzieć.', '1', 'youtube', ['Zbiory liczbowe. Oś liczbowa']],
['https://www.youtube.com/embed/QE7QM00MSVw', ['film-podstawa1'], 'Liceum.Klasa 1.Zbiory liczbowe.', '1', 'youtube', ['Zbiory liczbowe. Oś liczbowa']],
['https://www.youtube.com/embed/oC0k1mE5wIU', ['film-podstawa1', 'film-rozszerzenie1'], 'PRAWA DZIAŁAŃ W ZBIORZE LICZB RZECZYWISTYCH LEKCJE Z FSOREM #5', '1', 'youtube', ['Prawa działań w zbiorze liczb rzeczywistych']],
['https://www.youtube.com/embed/s_LHjcTJAZk', ['film-podstawa1', 'film-rozszerzenie1'], 'JAKIE SĄ PRAWA W ZBIORZE LICZB RZECZYWISTYCH?', '1', 'youtube', ['Prawa działań w zbiorze liczb rzeczywistych']],      
['https://www.youtube.com/embed/d47BJ23E8no', ['film-podstawa1', 'film-rozszerzenie1'], 'Liceum.Klasa1.Prawa działań', '1', 'youtube', ['Prawa działań w zbiorze liczb rzeczywistych']],
['https://www.youtube.com/embed/Hux9kRFSY4Q', ['film-podstawa1', 'film-rozszerzenie1'], 'PRZEDZIAŁY', '1', 'youtube', ['Przedziały']],
['https://www.youtube.com/embed/BfTA083UR_E', ['film-podstawa1', 'film-rozszerzenie1'], 'Liceum. Klasa 1. Przedziały', '1', 'youtube', ['Przedziały']],
['https://www.youtube.com/embed/LYSa0o1Tvhg', ['film-podstawa1', 'film-rozszerzenie1'], 'Przedziały liczbowe', '1', 'youtube', ['Przedziały']],
['https://www.youtube.com/embed/UQWZZ4ZlKjU', ['film-podstawa1', 'film-rozszerzenie1'], 'Działania na przedziałach', '1', 'youtube', ['Przedziały']],
['https://www.youtube.com/embed/pIDE6w9E2wE', ['film-podstawa1', 'film-rozszerzenie1'], 'PRZEDZIAŁY #4', '1', 'youtube', ['Przedziały']],
['https://www.youtube.com/embed/YxcohFIKyxA', ['film-podstawa1', 'film-rozszerzenie1'], 'ZBIÓR LICZB CAŁKOWITYCH I NATURALNYCH(przyda Ci się)', '1', 'youtube', ['Zbiór liczb naturalnych i zbiór liczb całkowitych']],
['https://www.youtube.com/embed/D77eRaqo6p8', ['film-podstawa1', 'film-rozszerzenie1'], 'Zbiory liczb naturalnych i całkowitych #3', '1', 'youtube', ['Zbiór liczb naturalnych i zbiór liczb całkowitych']],
['https://www.youtube.com/embed/y0_Z8GVtFmc', ['film-podstawa1', 'film-rozszerze1'], 'Działania na zbiorach liczbowych', '1', 'youtube', ['Zbiór liczb naturalnych i całkowitych']],
['https://www.youtube.com/embed/-MtRHUwIw5w', ['film-podstawa1', 'film-rozszerzenie1'], 'JAK ROZWIĄZAĆ RÓWNANIA (liniowe)', '1', 'youtube', ['Przypomnienie i uzupełnienie wiadomości o równaniach', 'Rozwiązywanie równań metodą równań równoważnych']],
['https://www.youtube.com/embed/CbirayNz4Bk', ['film-podstawa1', 'film-rozszerzenie1'], 'rozwiązywanie równań poziom 1', '1', 'youtube', ['Przypomnienie i uzupełnienie wiadomości o równaniach', 'Rozwiązywanie równań metodą równań równoważnych']],
['https://www.youtube.com/embed/S-IhtWiBbTw', ['film-podstawa1', 'film-rozszerzenie1'], 'Równania sprzeczne i tożsamościowe', '1', 'youtube', ['Przypomnienie i uzupełnienie wiadomości o równaniach', 'Rozwiązywanie równań metodą równań równoważnych']],
['https://www.youtube.com/embed/myxNBzuu1lw', ['film-podstawa1', 'film-rozszerzenie1'], 'rozwiązywanie równań poziom 3- przykłady z ułamkami', '1', 'youtube', ['Przypomnienie i uzupełnienie wiadomości o równaniach', 'Rozwiązywanie równań metodą równań równoważnych']],
['https://www.youtube.com/embed/1mdGC342mHk', ['film-postawa1', 'film-rozszerzenie1'], 'Obliczanie NWW i NWD + zadania tekstowe', '1', 'youtube', ['Przypomnienie i uzupełnienie wiadomości o równaniach']],
['https://www.youtube.com/embed/-MtRHUwIw5w', ['film-podstawa1', 'film-rozszerzenie1'], 'JAK ROZWIĄZAĆ RÓWNANIA (liniowe)', '1', 'youtube', ['Przypomnienie i uzupełnienie wiadomości o równaniach', 'Rozwiązywanie równań metodą równań równoważnych']],
['https://www.youtube.com/embed/wbOAr-QIVbI', ['film-podstawa1', 'film-rozszerzenie1'], 'JAK ROZWIĄZYWAĆ RÓWNANIA RÓWNOWAŻNE?', '1', 'youtube', ['Rozwiązywanie równań metodą równań równoważnych']],
['https://www.youtube.com/embed/JWmei9ad1WM', ['film-podstawa1', 'film-rozszerzenie1'], 'ROZWIĄZYWANIE NIERÓWNOŚCI Z JEDNĄ NIEWIADOMĄ', '1', 'youtube', ['Nierówności z jedną niewiadomą. Rozwiązywanie nierówności metodą nierówności równoważnych']],
['https://www.youtube.com/embed/dKZkTnEXVyA', ['film-podtsawa1', 'film-rozszerznie1'], 'Niezbędnik Maturzysty #4 Nierówności', '1', 'youtube', ['Nierówności z jedną niewiadomą. Rozwiązywanie nierówności metodą nierówności równoważnych']],
['https://www.youtube.com/embed/z07xfp-Yd8s', ['film-podtsawa1', 'film-rozszerznie1'], 'Matura 2020 zadanie 5. Nierówność ale nie ta społeczna', '1', 'youtube', ['Nierówności z jedną niewiadomą. Rozwiązywanie nierówności metodą nierówności równoważnych']],
['https://www.youtube.com/embed/Iag3pNZkfXI', ['film-podtsawa1', 'film-rozszerznie1'], 'Równania, nierówności, działania na zbiorach i przedziałach', '1', 'youtube', ['Nierówności z jedną niewiadomą. Rozwiązywanie nierówności metodą nierówności równoważnych']],
['https://www.youtube.com/embed/s1ciAwE2FwE', ['film-podstawa1', 'film-rozszerzenie1'], 'Obliczenia procentowe', '1', 'youtube', ['Procenty']],
['https://www.youtube.com/embed/2XCJdr5LvHw', ['film-podstawa1', 'film-rozszerzenie1'], 'Procenty na przykładzie procentów', '1', 'youtube', ['Procenty']],
['https://www.youtube.com/embed/decCqM9MqE0', ['film-podstawa1', 'film-rozszerzenie1'], 'PROCENTY', '1', 'youtube', ['Procenty']],
['https://www.youtube.com/embed/FzP1CMS-4LE', ['film-podstawa1', 'film-rozszerzenie1'], 'Zadanie maturalne- procenty a punkty procentowe', '1', 'youtube', ['Punkty procentowe']],
['https://www.youtube.com/embed/Y4F4ScNJ9Qo', ['film-podstawa1', 'film-rozszerzenie1'], 'Liceum.Klasa I. Procenty i punkty procentowe', '1', 'youtube', ['Punkty procentowe']],
['https://www.youtube.com/embed/oqb0yu3OCW4', ['film-podstawa1', 'film-rozszerzenie1'], 'PUNKTY PROCENTOWE - co musisz wiedzieć', '1', 'youtube', ['Punkty procentowe']],
['https://www.youtube.com/embed/yZnqypkUqDA', ['film-podstawa1', 'film-rozszerzenie1'], 'Liceum.Klasa I. Błąd względny i bezwzględny', '1', 'youtube', ['Przybliżenia, błąd bezwzględny i błąd względny, szacowanie']],
['https://www.youtube.com/embed/i9FT3VyeOBc', ['film-podstawa1', 'film-rozszerzenie1'], 'PRZYBLIŻENIE I SZACOWANIE', '1', 'youtube', ['Przybliżenia, błąd bezwzględny i błąd względny, szacowanie']],
];
export function shuffle(array) {
  let currentIndex = array.length,
    randomIndex;
  while (currentIndex > 0) {
    randomIndex = Math.floor(Math.random() * currentIndex);
    currentIndex--;
    [array[currentIndex], array[randomIndex]] = [
      array[randomIndex],
      array[currentIndex],
    ];
  }
  return array;
}
filmyYtLinki = shuffle(filmyYtLinki);
export default filmyYtLinki;
