export type filmy = [string, string[], string, string, string, string[]];

let filmyYtLinki:filmy[] = [
/*['https://www.youtube.com/embed/naq9D6jvnhA', ['film-podstawa2', 'film-rozszerzenie2'], 'Matematyka - Wielomiany jednej zmiennej (część I)', '8', 'youtube'],
['https://www.youtube.com/embed/ev_-R-3W_yo', ['film-podstawa2', 'film-rozszerzenie2'], 'Co to jest wielomian? #1 [ Wielomiany ]', '8', 'youtube'],
['https://www.youtube.com/embed/V2D8wYNpAk8', ['film-podstawa2', 'film-rozszerzenie2'], 'Dodawanie i odejmowanie wielomianów', '8', 'youtube'],
['https://www.youtube.com/embed/VZA09ymFcV4', ['film-podstawa2', 'film-rozszerzenie2'], 'Szybko i na temat. Dzielenie Wielomianów Krok po Kroku', '8', 'youtube'],
['https://www.youtube.com/embed/77CgfPFONWE', ['film-podstawa2', 'film-rozszerzenie2'], 'Sprawdzian na 5!WIELOMIANY (rozkład na czynniki, dzielenie, Horner, równania, TW o reszcie/Bézouta)', '8', 'youtube'],
['https://www.youtube.com/embed/KLjji_I3XvA', ['film-podstawa2', 'film-rozszerzenie2'], 'Liceum. Klasa II. Wielomiany. Nierówności wielomianowe', '8', 'youtube'],
['https://www.youtube.com/embed/vQgrdSAjYaE', ['film-podstawa2', 'film-rozszerzenie2'], 'Dodawanie, odejmowanie i mnożenie wielomianów #3 [ Wielomiany ]', '8', 'youtube'],
['https://www.youtube.com/embed/f_Kv7-oiMLw', ['film-podstawa2', 'film-rozszerzenie2'], 'WSZYSTKO o: NIERÓWNOŚCI WIELOMIANOWE. Jak rysować wykres wielomianu?Co to jest krotność pierwiastka?', '8', 'youtube'],
['https://www.youtube.com/embed/5UaDP_fF8hY', ['film-rozszerzenie2'], 'Wielomiany co trzeba ogarniać? Matura Matematyka Rozszerzenie', '8', 'youtube'],
['https://www.youtube.com/embed/eQTEXfqLQYE', ['film-podstawa2', 'film-rozszerzenie2'], 'Wzory skróconego mnożenia - sześcian sumy i różnicy.', '8', 'youtube'],
['https://www.youtube.com/embed/ehRXj3GEpIw', ['film-rozszerzenie2'], 'Matura rozszerzona - kurs - wzory skróconego mnożenia', '8', 'youtube'],
['https://www.youtube.com/embed/Q-lkLAeKtlA', ['film-podstawa2', 'film-rozszerzenie2'], 'Jak dzielić (pisemnie) WIELOMIAN przez DWUMIAN na MATURZE PODSTAWOWEJ?', '8', 'youtube'],
['https://www.youtube.com/embed/9piOqP5jcw4', ['film-podstawa2', 'film-rozszerzenie2'], 'Dzielenie wielomianów #4 [ Wielomiany ]', '8', 'youtube'],
['https://www.youtube.com/embed/msfZ8_eHIoM', ['film-podstawa2', 'film-rozszerzenie2'], 'Pierwiastki całkowite oraz wymierne wielomianu #8 [ Wielomiany ]', '8', 'youtube'],
['https://www.youtube.com/embed/5ywgT7USp4Y', ['film-rozszerzenie2'], 'Wielomiany na poziomie rozszerzonym', '8', 'youtube'],
['https://www.youtube.com/embed/KPOFrG8HOwo', ['film-podstawa2', 'film-rozszerzenie2'], 'WEKTOR w układzie współrzędnych', '1', 'youtube'],
['https://www.youtube.com/embed/LqBrQp-f2I0', ['film-podstawa2', 'film-rozszerzenie2'], 'Wektory - Wprowadzenie Odc.1 (na szybko bo wychodzę za 5 min)', '1', 'youtube'],
['https://www.youtube.com/embed/WCOChZ-BaCM', ['film-rozszerzenie2'], 'Wektory - wprowadzenie - najważniejsze informacje', '1', 'youtube'],
['https://www.youtube.com/embed/9agT9Lu6pJQ', ['film-podstawa2', 'film-rozszerzenie2'], 'Liceum. Klasa I. Wektor w układzie współrzędnych', '1', 'youtube'],
['https://www.youtube.com/embed/C3RlRjnBE0c', ['film-podstawa2', 'film-rozszerzenie2'], 'Przesuwanie wykresów funkcji wzdłuż osi X i Y oraz o wektor', '1', 'youtube'],
['https://www.youtube.com/embed/sD4mC5Ux6pM', ['film-podstawa2', 'film-rozszerzenie2'], 'Przesuwanie wykresu funkcji wzdłuż osi OX i OY', '1', 'youtube'],
['https://www.youtube.com/embed/7xxIkATsBeo', ['film-podstawa2', 'film-rozszerzenie2'], 'Przesunięcie wykresu funkcji wzdłuż osi układu współrzędnych cz.2 MATEMATYKA LEKCJE Z FSORE', '1', 'youtube'],
['https://www.youtube.com/embed/nxuZvjTxMOk', ['film-podstawa2', 'film-rozszerzenie2'], 'Matematyka - Przesunięcie funkcji wzdłuż osi OX', '1', 'youtube'],
['https://www.youtube.com/embed/WMVe1NZBrsE', ['film-podstawa2', 'film-rozszerzenie2'], 'Przesuwanie funkcji w górę, w dół, w prawo, w lewo | MatFiz24.PL', '1', 'youtube'],
['https://www.youtube.com/embed/yLRIkacEAy0', ['film-podstawa2', 'film-rozszerzenie2'], 'Przekształcanie wykresu funkcji - symetria względem osi OX i OY', '1', 'youtube'],
['https://www.youtube.com/embed/Q-0ylc-dqn8', ['film-podstawa2', 'film-rozszerzenie2'], 'Symetria osiowa względem osi OX i OY - definicje, przykłady', '1', 'youtube'],
['https://www.youtube.com/embed/m48o2yHJoDA', ['film-podstawa2', 'film-rozszerzenie2'], 'Symetria osiowa w układzie współrzędnych #3 [ Symetria ]', '1', 'youtube'],
['https://www.youtube.com/embed/H9i1y9Hdtl4', ['film-podstawa2', 'film-rozszerzenie2'], 'Liceum. Klasa I. Symetria środkowa i osiowa w układzie współrzędnych', '1', 'youtube'],
['https://www.youtube.com/embed/dPZVFCuQCvI', ['film-podstawa2', 'film-rozszerzenie2'], 'Symetria środkowa. Symetria środkowa względem punktu (0,0) - definicje, przykłady', '1', 'youtube'],
['https://www.youtube.com/embed/qCqHk3kFGZo', ['film-podstawa2', 'film-rozszerzenie2'], 'Symetria środkowa względem punktu 0(0,0)', '1', 'youtube'],
['https://www.youtube.com/embed/4S0vLLSkcBs', ['film-podstawa2', 'film-rozszerzenie2'], 'Symetria środkowa w układzie współrzędnych #6 [ Symetria ]', '1', 'youtube'],*/
['https://www.youtube.com/embed/uMRFEP8yQTg', ['film-rozszerzenie2'], 'Własności wartości bezwzględnej LEKCJE Z FSOREM #82 ROZSZERZENIE', '2', 'youtube', ['Własności wartości bezwzględnej']],
['https://www.youtube.com/embed/ByV7VITIEzA', ['film-rozszerzenie2'], 'Matematyka - Własności wartości bezwzględnej', '2', 'youtube', ['Własności wartości bezwzględnej']],
['https://www.youtube.com/embed/R3um24WEGvU', ['film-rozszerzenie2'], 'Wartość bezwzględna na ROZSZERZENIU: Równania i nierówności z JEDNYM modułem', '2', 'youtube', ['Równania z wartością bezwzględną', 'Nierówności z wartością bezwzględną']],
['https://www.youtube.com/embed/JWYCRqjReDo', ['film-rozszerzenie2'], 'Wartość bezwzględna na ROZSZERZENIU: Równania i nierówności z DWOMA modułami', '2', 'youtube', ['Równania z wartością bezwzględną', 'Nierówności z wartością bezwzględną']],
['https://www.youtube.com/embed/SvhWh9DeHI4', ['film-podstawa1', 'film-rozszerzenie1'], 'Działania na zbiorach', '1', 'youtube', ['Zbiór. Działania na zbiorach']],
['https://www.youtube.com/embed/Z7qMR5ay8Zg', ['film-podstawa1', 'film-rozszerzenie1'], 'Szybko i na temat. Zbiory + Zadania.', '1', 'youtube', ['Zbiór. Działania na zbiorach']],
['https://www.youtube.com/embed/g0Rk_OTvb_o', ['film-podstawa1', 'film-rozszerzenie1'], 'ZBIORY LICZBOWE I OŚ LICZBOWA - wszystko co musisz wiedzieć.', '1', 'youtube', ['Zbiory liczbowe. Oś liczbowa']],
['https://www.youtube.com/embed/QE7QM00MSVw', ['film-podstawa1', 'film-rozszerzenie1'], 'Liceum.Klasa 1.Zbiory liczbowe.', '1', 'youtube', ['Zbiory liczbowe. Oś liczbowa']],
['https://www.youtube.com/embed/oC0k1mE5wIU', ['film-podstawa1', 'film-rozszerzenie1'], 'PRAWA DZIAŁAŃ W ZBIORZE LICZB RZECZYWISTYCH LEKCJE Z FSOREM #5', '1', 'youtube', ['Prawa działań w zbiorze liczb rzeczywistych']],
['https://www.youtube.com/embed/s_LHjcTJAZk', ['film-podstawa1', 'film-rozszerzenie1'], 'JAKIE SĄ PRAWA W ZBIORZE LICZB RZECZYWISTYCH?', '1', 'youtube', ['Prawa działań w zbiorze liczb rzeczywistych']],      
['https://www.youtube.com/embed/d47BJ23E8no', ['film-podstawa1', 'film-rozszerzenie1'], 'Liceum.Klasa1.Prawa działań', '1', 'youtube', ['Prawa działań w zbiorze liczb rzeczywistych']],
['https://www.youtube.com/embed/Hux9kRFSY4Q', ['film-podstawa1', 'film-rozszerzenie1'], 'PRZEDZIAŁY', '1', 'youtube', ['Przedziały']],
['https://www.youtube.com/embed/BfTA083UR_E', ['film-podstawa1', 'film-rozszerzenie1'], 'Liceum. Klasa 1. Przedziały', '1', 'youtube', ['Przedziały']],
['https://www.youtube.com/embed/LYSa0o1Tvhg', ['film-podstawa1', 'film-rozszerzenie1'], 'Przedziały liczbowe', '1', 'youtube', ['Przedziały']],
['https://www.youtube.com/embed/UQWZZ4ZlKjU', ['film-podstawa1', 'film-rozszerzenie1'], 'Działania na przedziałach', '1', 'youtube', ['Przedziały']],
['https://www.youtube.com/embed/pIDE6w9E2wE', ['film-podstawa1', 'film-rozszerzenie1'], 'PRZEDZIAŁY #4', '1', 'youtube', ['Przedziały']],
['https://www.youtube.com/embed/YxcohFIKyxA', ['film-podstawa1', 'film-rozszerzenie1'], 'ZBIÓR LICZB CAŁKOWITYCH I NATURALNYCH(przyda Ci się)', '1', 'youtube', ['Zbiór liczb naturalnych i zbiór liczb całkowitych']],
['https://www.youtube.com/embed/D77eRaqo6p8', ['film-podstawa1', 'film-rozszerzenie1'], 'Zbiory liczb naturalnych i całkowitych #3', '1', 'youtube', ['Zbiór liczb naturalnych i zbiór liczb całkowitych']],
['https://www.youtube.com/embed/y0_Z8GVtFmc', ['film-podstawa1', 'film-rozszerzenie1'], 'Działania na zbiorach liczbowych', '1', 'youtube', ['Zbiór liczb naturalnych i całkowitych']],
['https://www.youtube.com/embed/-MtRHUwIw5w', ['film-podstawa1', 'film-rozszerzenie1'], 'JAK ROZWIĄZAĆ RÓWNANIA (liniowe)', '1', 'youtube', ['Przypomnienie i uzupełnienie wiadomości o równaniach', 'Rozwiązywanie równań metodą równań równoważnych']],
['https://www.youtube.com/embed/CbirayNz4Bk', ['film-podstawa1', 'film-rozszerzenie1'], 'rozwiązywanie równań poziom 1', '1', 'youtube', ['Przypomnienie i uzupełnienie wiadomości o równaniach', 'Rozwiązywanie równań metodą równań równoważnych']],
['https://www.youtube.com/embed/S-IhtWiBbTw', ['film-podstawa1', 'film-rozszerzenie1'], 'Równania sprzeczne i tożsamościowe', '1', 'youtube', ['Przypomnienie i uzupełnienie wiadomości o równaniach', 'Rozwiązywanie równań metodą równań równoważnych']],
['https://www.youtube.com/embed/myxNBzuu1lw', ['film-podstawa1', 'film-rozszerzenie1'], 'rozwiązywanie równań poziom 3- przykłady z ułamkami', '1', 'youtube', ['Przypomnienie i uzupełnienie wiadomości o równaniach', 'Rozwiązywanie równań metodą równań równoważnych']],
['https://www.youtube.com/embed/1mdGC342mHk', ['film-podstawa1', 'film-rozszerzenie1'], 'Obliczanie NWW i NWD + zadania tekstowe', '1', 'youtube', ['Przypomnienie i uzupełnienie wiadomości o równaniach']],
['https://www.youtube.com/embed/-MtRHUwIw5w', ['film-podstawa1', 'film-rozszerzenie1'], 'JAK ROZWIĄZAĆ RÓWNANIA (liniowe)', '1', 'youtube', ['Przypomnienie i uzupełnienie wiadomości o równaniach', 'Rozwiązywanie równań metodą równań równoważnych']],
['https://www.youtube.com/embed/wbOAr-QIVbI', ['film-podstawa1', 'film-rozszerzenie1'], 'JAK ROZWIĄZYWAĆ RÓWNANIA RÓWNOWAŻNE?', '1', 'youtube', ['Rozwiązywanie równań metodą równań równoważnych']],
['https://www.youtube.com/embed/JWmei9ad1WM', ['film-podstawa1', 'film-rozszerzenie1'], 'ROZWIĄZYWANIE NIERÓWNOŚCI Z JEDNĄ NIEWIADOMĄ', '1', 'youtube', ['Nierówność z jedną niewiadomą. Rozwiązywanie nierówności metodą nierówności równoważnych']],
['https://www.youtube.com/embed/dKZkTnEXVyA', ['film-podstawa1', 'film-rozszerzenie1'], 'Niezbędnik Maturzysty #4 Nierówności', '1', 'youtube', ['Nierówność z jedną niewiadomą. Rozwiązywanie nierówności metodą nierówności równoważnych']],
['https://www.youtube.com/embed/z07xfp-Yd8s', ['film-podstawa1', 'film-rozszerzenie1'], 'Matura 2020 zadanie 5. Nierówność ale nie ta społeczna', '1', 'youtube', ['Nierówność z jedną niewiadomą. Rozwiązywanie nierówności metodą nierówności równoważnych']],
['https://www.youtube.com/embed/Iag3pNZkfXI', ['film-podstawa1', 'film-rozszerzenie1'], 'Równania, nierówności, działania na zbiorach i przedziałach', '1', 'youtube', ['Nierówność z jedną niewiadomą. Rozwiązywanie nierówności metodą nierówności równoważnych']],
['https://www.youtube.com/embed/s1ciAwE2FwE', ['film-podstawa1', 'film-rozszerzenie1'], 'Obliczenia procentowe', '1', 'youtube', ['Procenty']],
['https://www.youtube.com/embed/2XCJdr5LvHw', ['film-podstawa1', 'film-rozszerzenie1'], 'Procenty na przykładzie procentów', '1', 'youtube', ['Procenty']],
['https://www.youtube.com/embed/decCqM9MqE0', ['film-podstawa1', 'film-rozszerzenie1'], 'PROCENTY', '1', 'youtube', ['Procenty']],
['https://www.youtube.com/embed/FzP1CMS-4LE', ['film-podstawa1', 'film-rozszerzenie1'], 'Zadanie maturalne- procenty a punkty procentowe', '1', 'youtube', ['Punkty procentowe']],
['https://www.youtube.com/embed/Y4F4ScNJ9Qo', ['film-podstawa1', 'film-rozszerzenie1'], 'Liceum.Klasa I. Procenty i punkty procentowe', '1', 'youtube', ['Punkty procentowe']],
['https://www.youtube.com/embed/oqb0yu3OCW4', ['film-podstawa1', 'film-rozszerzenie1'], 'PUNKTY PROCENTOWE - co musisz wiedzieć', '1', 'youtube', ['Punkty procentowe']],
['https://www.youtube.com/embed/yZnqypkUqDA', ['film-podstawa1', 'film-rozszerzenie1'], 'Liceum.Klasa I. Błąd względny i bezwzględny', '1', 'youtube', ['Przybliżenia, błąd bezwzględny i błąd względny, szacowanie']],
['https://www.youtube.com/embed/i9FT3VyeOBc', ['film-podstawa1', 'film-rozszerzenie1'], 'PRZYBLIŻENIE I SZACOWANIE', '1', 'youtube', ['Przybliżenia, błąd bezwzględny i błąd względny, szacowanie']],
["https://www.youtube.com/embed/ByLFgCWT5po",["film-podstawa1","film-rozszerzenie1"],"POTĘGA O WYKŁADNIKU NATURALNYM",'2',"youtube",["Potęga o wykładniku naturalnym"]],
["https://www.youtube.com/embed/cKoLn_EELrM",["film-podstawa1","film-rozszerzenie1"],"Pojęcie potęgi #1 [ Potęgi o wykładniku naturalnym ]",'2',"youtube",["Potęga o wykładniku naturalnym"]],
["https://www.youtube.com/embed/j8ioOqkaVn4",["film-podstawa1","film-rozszerzenie1"]," Potęgowanie ułamków #2 [ Potęgi o wykładniku naturalnym ]",'2',"youtube",["Potęga o wykładniku naturalnym"]],
["https://www.youtube.com/embed/J0r7extoQN0",["film-podstawa1","film-rozszerzenie1"],"Potęga potęgi #6 [ Potęgi o wykładniku naturalnym ]",'2',"youtube",["Potęga o wykładniku naturalnym"]],
["https://www.youtube.com/embed/XxYHD8va23o",["film-podstawa1","film-rozszerzenie1"]," Działania na potęgach o wykładniku naturalnym #12 [ Potęgi o wykładniku naturalnym ]",'2',"youtube",["Potęga o wykładniku naturalnym"]],
["https://www.youtube.com/embed/RLvWy3p_-7k",["film-podstawa1","film-rozszerzenie1"],"Potęga o wykładniku naturalnym część 1 WSTĘP LEKCJE Z FSOREM #14",'2',"youtube",["Potęga o wykładniku naturalnym"]],
["https://www.youtube.com/embed/HNKoD6txmXM",["film-podstawa1","film-rozszerzenie1"]," Potęga o wykładniku naturalnym część 2 ZADANKA LEKCJE Z FSOREM #15",'2',"youtube",["Potęga o wykładniku naturalnym"]],
["https://www.youtube.com/embed/WonRDbTDyKo",["film-podstawa1","film-rozszerzenie1"],"DZIAŁANIA NA PIERWIASTKACH [#14]",'2',"youtube",["Pierwiastek arytmetyczny. Pierwiastek stopnia nieparzystego z liczby ujemnej"]],
["https://www.youtube.com/embed/ct_T7suAO8E",["film-podstawa1","film-rozszerzenie1"],"własności pierwiastków powtórzenie część 1",'2',"youtube",["Pierwiastek arytmetyczny. Pierwiastek stopnia nieparzystego z liczby ujemnej"]],
["https://www.youtube.com/embed/czlNDea2iWE",["film-podstawa1","film-rozszerzenie1"],"własności pierwiastków część 2",'2',"youtube",["Pierwiastek arytmetyczny. Pierwiastek stopnia nieparzystego z liczby ujemnej"]],
["https://www.youtube.com/embed/7TEcnG-E28A",["film-podstawa1","film-rozszerzenie1"],"Działania na pierwiastkach wyższych stopni #2 [Potęgi i pierwiastki]",'2',"youtube",["Pierwiastek arytmetyczny. Pierwiastek stopnia nieparzystego z liczby ujemnej"]],
["https://www.youtube.com/embed/gWV-PMujzI4",["film-podstawa1","film-rozszerzenie1"],"Liceum.Klasa.I.Potęgi i pierwiastki",'2',"youtube",["Pierwiastek arytmetyczny. Pierwiastek stopnia nieparzystego z liczby ujemnej"]],
["https://www.youtube.com/embed/Cq09pCwAa1Q",["film-podstawa1","film-rozszerzenie1"],"Pierwiastek arytmetyczny stopnia parzystego i nieparzystego LEKCJE Z FSOREM #16",'2',"youtube",["Pierwiastek arytmetyczny. Pierwiastek stopnia nieparzystego z liczby ujemnej"]],
["https://www.youtube.com/embed/oT8Dkkj_Duc",["film-podstawa1","film-rozszerzenie1"],"DZIAŁANIA NA WYRAŻENIACH ALGEBRAICZNYCH #14",'2',"youtube",["Działania na wyrażeniach algebraicznych"]],
["https://www.youtube.com/embed/Vm4FK_O1OV4",["film-podstawa1","film-rozszerzenie1"],"Wyrażenia algebraiczne - wprowadzenie #1 [ Wyrażenia algebraiczne ]",'2',"youtube",["Działania na wyrażeniach algebraicznych"]],
["https://www.youtube.com/embed/rQ3eHU0OxuQ",["film-podstawa1","film-rozszerzenie1"],"Wyrażenia algebraiczne - suma różnica, iloczyn, iloraz #2 [ Wyrażenia algebraiczne ]",'2',"youtube",["Działania na wyrażeniach algebraicznych"]],
["https://www.youtube.com/embed/nysijB3-IgA",["film-podstawa1","film-rozszerzenie1"],"Wyrażenia algebraiczne - nazywanie i odczytywanie #3 [ Wyrażenia algebraiczne ]",'2',"youtube",["Działania na wyrażeniach algebraicznych"]],
["https://www.youtube.com/embed/IPgy5oW7Ztw",["film-podstawa1","film-rozszerzenie1"],"Wyrażenia algebraiczne- część I",'2',"youtube",["Działania na wyrażeniach algebraicznych"]],
["https://www.youtube.com/embed/VHMnzpMaahk",["film-podstawa1","film-rozszerzenie1"],"WZORY SKRÓCONEGO MNOŻENIA [#15]",'2',"youtube",["Wzory skróconego mnożenia stopnia 2"]],
["https://www.youtube.com/embed/l2dUrcYVofs",["film-podstawa1","film-rozszerzenie1"],"wzory skróconego mnożenia #1",'2',"youtube",["Wzory skróconego mnożenia stopnia 2"]],
["https://www.youtube.com/embed/luDwfx-24UQ",["film-podstawa1","film-rozszerzenie1"],"wzory skróconego mnożenia #3",'2',"youtube",["Wzory skróconego mnożenia stopnia 2"]],
["https://www.youtube.com/embed/NZ4eldiDuFY",["film-podstawa1","film-rozszerzenie1"],"wzory skróconego mnożenia #4",'2',"youtube",["Wzory skróconego mnożenia stopnia 2"]],
["https://www.youtube.com/embed/QXMyt0HMYds",["film-podstawa1","film-rozszerzenie1"],"POTĘGA O WYKŁADNIKU CAŁKOWITYM UJEMNYM [#16]",'2',"youtube",["Potęga o wykładniku całkowitym ujemnym"]],
["https://www.youtube.com/embed/IHfclHCfZ-I",["film-podstawa1","film-rozszerzenie1"],"Potęga o wykładniku całkowitym ujemnym",'2',"youtube",["Potęga o wykładniku całkowitym ujemnym"]],
["https://www.youtube.com/embed/E4N4tk-JegI",["film-podstawa1","film-rozszerzenie1"],"Potęga o wykładniku całkowitym ujemnym ZADANKA Z FSOREM #21",'2',"youtube",["Potęga o wykładniku całkowitym ujemnym"]],
["https://www.youtube.com/embed/XNRpiSxOP_4",["film-podstawa1","film-rozszerzenie1"],"POTĘGA O WYKŁADNIKU WYMIERNYM [#17]",'2',"youtube",["Potęga o wykładniku wymiernym"]],
["https://www.youtube.com/embed/-kc52o2gD4Y",["film-podstawa1","film-rozszerzenie1"],"Potęga o wykładniku wymiernym",'2',"youtube",["Potęga o wykładniku wymiernym"]],
["https://www.youtube.com/embed/MI4DFB6yw7M",["film-podstawa1","film-rozszerzenie1"],"Potęga o wykładniku wymiernym LEKCJE Z FSOREM #22",'2',"youtube",["Potęga o wykładniku wymiernym"]],
["https://www.youtube.com/embed/rbQZJV736XE",["film-podstawa1","film-rozszerzenie1"],"Działania na potęgach o wykładniku wymiernym #4 [Potęgi i pierwiastki]",'2',"youtube",["Potęga o wykładniku wymiernym"]],
["https://www.youtube.com/embed/YhrxtN1cpro",["film-podstawa1","film-rozszerzenie1"],"POTĘGA RZECZYWISTA - to musisz wiedzieć",'2',"youtube",["Potęga o wykładniku rzeczywistym"]],
["https://www.youtube.com/embed/ClKPtUxFybY",["film-podstawa1","film-rozszerzenie1"],"OBLICZANIE LOGARYTMÓW #19",'2',"youtube",["Określenie logarytmu","Zastosowanie logarytmów"]],
["https://www.youtube.com/embed/K3OkbCo-Xew",["film-podstawa1","film-rozszerzenie1"],"Obliczanie logarytmów- podstawy",'2',"youtube",["Określenie logarytmu","Zastosowanie logarytmów"]],
["https://www.youtube.com/embed/BvMBskQrRqs",["film-podstawa1","film-rozszerzenie1"],"Obliczanie logarytmów #2",'2',"youtube",["Określenie logarytmu","Zastosowanie logarytmów"]],
["https://www.youtube.com/embed/bUPcSqLBRMQ",["film-podstawa1","film-rozszerzenie1"],"Własności logarytmów",'2',"youtube",["Określenie logarytmu","Zastosowanie logarytmów"]],
["https://www.youtube.com/embed/LkjNsFxt9us",["film-podstawa1","film-rozszerzenie1"],"Własności logarytmów #2",'2',"youtube",["Określenie logarytmu","Zastosowanie logarytmów"]],
["https://www.youtube.com/embed/dekaP1GmmQE",["film-podstawa1","film-rozszerzenie1"],"Definicja logarytmu #1 [Logarytmy]",'2',"youtube",["Określenie logarytmu","Zastosowanie logarytmów"]],
["https://www.youtube.com/embed/HtXEd0OWCFo",["film-podstawa1","film-rozszerzenie1"],"Dodawanie i odejmowanie logarytmów #2 [Logarytmy]",'2',"youtube",["Określenie logarytmu","Zastosowanie logarytmów"]],
["https://www.youtube.com/embed/gXvrjyM0mpU",["film-podstawa1","film-rozszerzenie1"],"Logarytm potęgi #3 [Logarytmy]",'2',"youtube",["Określenie logarytmu","Zastosowanie logarytmów"]],
["https://www.youtube.com/embed/xfkjvB66Ex0",["film-podstawa1","film-rozszerzenie1"],"Logarytm w wykładniku potęgi #4 [Logarytmy]",'2',"youtube",["Określenie logarytmu","Zastosowanie logarytmów"]],
["https://www.youtube.com/embed/ACrRHluVm_o",["film-podstawa1","film-rozszerzenie1"],"Zmiana podstawy logarytmu #5 [Logarytmy]",'2',"youtube",["Określenie logarytmu","Zastosowanie logarytmów"]],
["https://www.youtube.com/embed/VANUPgaNSPA",["film-podstawa1","film-rozszerzenie1"],"Działania na logarytmach #6 [Logarytmy]",'2',"youtube",["Określenie logarytmu","Zastosowanie logarytmów"]],
["https://www.youtube.com/embed/0Yb67WnLd1I",["film-podstawa1","film-rozszerzenie1"],"Proste równania logarytmiczne #7 [Logarytmy]",'2',"youtube",["Określenie logarytmu","Zastosowanie logarytmów"]],
["https://www.youtube.com/embed/1euY8qqQB0Q",["film-podstawa1","film-rozszerzenie1"],"Liceum.Klasa.I.Logarytmy",'2',"youtube",["Określenie logarytmu","Zastosowanie logarytmów"]],
["https://www.youtube.com/embed/uojszTHc-Ug",["film-podstawa1","film-rozszerzenie1"],"Logarytmy prawie od zera odc.1 Zadania (Udostępnij na grupie klasowej)",'2',"youtube",["Określenie logarytmu","Zastosowanie logarytmów"]],
["https://www.youtube.com/embed/3doMk6eSaNw",["film-podstawa1","film-rozszerzenie1"],"ZDANIA LOGICZNE W MATEMATYCE #20",'2',"youtube",["Zdanie. Zaprzeczenie zdania"]],
["https://www.youtube.com/embed/eXJD9cHcgD4",["film-podstawa1","film-rozszerzenie1"],"Liceum. Klasa I. Zdania",'2',"youtube",["Zdanie. Zaprzeczenie zdania"]],
["https://www.youtube.com/embed/vyjnc4fHtUI",["film-podstawa1","film-rozszerzenie1"],"Liceum. Klasa I. Kwantyfikatory",'2',"youtube",["Zdanie. Zaprzeczenie zdania"]],
["https://www.youtube.com/embed/NnqeawOqGlI",["film-podstawa1","film-rozszerzenie1"],"ZDANIA ZŁOŻONE Z MATEMATYKI [#21]",'2',"youtube",["Zdania złożone. Zaprzeczenia zdań złożonych"]],
["https://www.youtube.com/embed/1-l5V8STyjE",["film-podstawa1","film-rozszerzenie1"],"Liceum.Klasa I. Zdania złożone",'2',"youtube",["Zdania złożone. Zaprzeczenia zdań złożonych"]],
["https://www.youtube.com/embed/N35gKqBdsRA",["film-podstawa1","film-rozszerzenie1"],"DOWODY I TWIERDZENIA W MATEMATYCE",'2',"youtube",["Definicja. Twierdzenie. Dowód twierdzenia"]],
["https://www.youtube.com/embed/o7bAaI1Fhxo",["film-podstawa1","film-rozszerzenie1"],"Dowodzenie nierówności #1",'2',"youtube",["Definicja. Twierdzenie. Dowód twierdzenia"]],
["https://www.youtube.com/embed/nHUJSncnPu0",["film-podstawa1","film-rozszerzenie1"],"Dowodzenie nierówności #2",'2',"youtube",["Definicja. Twierdzenie. Dowód twierdzenia"]],
["https://www.youtube.com/embed/SVEYxWjSOQU",["film-podstawa1","film-rozszerzenie1"],"Dowodzenie nierówności #3",'2',"youtube",["Definicja. Twierdzenie. Dowód twierdzenia"]],
["https://www.youtube.com/embed/LeH8NfKbzLw",["film-podstawa1","film-rozszerzenie1"],"Dowodzenie nierówności #4",'2',"youtube",["Definicja. Twierdzenie. Dowód twierdzenia"]],
["https://www.youtube.com/embed/uP-fC_2zY8U",["film-podstawa1","film-rozszerzenie1"],"MATURA MATEMATYKA Dowody algebraiczne Zadania PEWNIAK",'2',"youtube",["Definicja. Twierdzenie. Dowód twierdzenia"]],
["https://www.youtube.com/embed/IYZwcMqXajU",["film-podstawa1","film-rozszerzenie1"],"PRZEKSZTAŁCANIE WZORÓW [#23]",'2',"youtube",["Przekształcanie wzorów"]],
["https://www.youtube.com/embed/zXk4QJGImQs",["film-podstawa1","film-rozszerzenie1"],"przekształcanie wzorów część 1",'2',"youtube",["Przekształcanie wzorów"]],
["https://www.youtube.com/embed/tMN6aEsOLDo",["film-podstawa1","film-rozszerzenie1"],"przekształcanie wzorów część 2",'2',"youtube",["Przekształcanie wzorów"]],
["https://www.youtube.com/embed/qaCVyvlWn5I",["film-podstawa1","film-rozszerzenie1"],"Przekształcanie wzorów #9 [ Równania ]",'2',"youtube",["Przekształcanie wzorów"]],
["https://www.youtube.com/embed/XjC_rvfVjy4",["film-podstawa1","film-rozszerzenie1"],"Przekształcanie wzorów LEKCJE Z FSOREM #25",'2',"youtube",["Przekształcanie wzorów"]],
["https://www.youtube.com/embed/Fy3GWyJzjJU",["film-podstawa1","film-rozszerzenie1"],"ŚREDNIE W MATEMATYCE [#24]",'2',"youtube",["Średnie"]],
["https://www.youtube.com/embed/8r9Vnk1yyBI",["film-podstawa1","film-rozszerzenie1"],"CZYM SĄ FUNKCJE W MATEMATYCE? [#25]",'3',"youtube",["Pojęcie funkcji. Funkcja liczbowa. Sposoby opisywania funkcji"]],
["https://www.youtube.com/embed/9JDTeWzOdXs",["film-podstawa1","film-rozszerzenie1"],"funkcje powtórzenie",'3',"youtube",["Pojęcie funkcji. Funkcja liczbowa. Sposoby opisywania funkcji"]],
["https://www.youtube.com/embed/PY6KCFwVJ0E",["film-podstawa1","film-rozszerzenie1"],"Co to jest funkcja #1 [ FUNKCJA ]",'3',"youtube",["Pojęcie funkcji. Funkcja liczbowa. Sposoby opisywania funkcji"]],
["https://www.youtube.com/embed/U2cq3ajIZro",["film-podstawa1","film-rozszerzenie1"],"Liceum. Klasa I. Wstęp do funkcji",'3',"youtube",["Pojęcie funkcji. Funkcja liczbowa. Sposoby opisywania funkcji"]],
["https://www.youtube.com/embed/fheOaJ8YfyE",["film-podstawa1","film-rozszerzenie1"],"Funkcja co to takiego? Wstęp, definicja, podstawowe pojęcia LEKCJA Z FSOREM #29",'3',"youtube",["Pojęcie funkcji. Funkcja liczbowa. Sposoby opisywania funkcji"]],
["https://www.youtube.com/embed/mG8BVf7Xu18",["film-podstawa1","film-rozszerzenie1"],"Wykresy funkcji #5 [ Własności funkcji ]",'3',"youtube",["Wykres funkcji"]],
["https://www.youtube.com/embed/4WQfTf83qY8",["film-podstawa1","film-rozszerzenie1"],"Wykres funkcji LEKCJE Z FSOREM #30",'3',"youtube",["Wykres funkcji"]],
["https://www.youtube.com/embed/807jY8q-YKc",["film-podstawa1","film-rozszerzenie1"],"JAK WYZNACZYĆ DZIEDZINĘ FUNKCJI? [#27]",'3',"youtube",["Dziedzina funkcji liczbowej"]],
["https://www.youtube.com/embed/aMA2oFxiqsE",["film-podstawa1","film-rozszerzenie1"],"Dziedzina i zbiór wartości funkcji #2 [Własności funkcji]",'3',"youtube",["Dziedzina funkcji liczbowej","Zbiór wartości funkcji liczbowej. Najmniejsza i największa wartość funkcji"]],
["https://www.youtube.com/embed/RhzTgd97aRs",["film-podstawa1","film-rozszerzenie1"],"Liceum. Klasa I. Dziedzina i zbiór wartości funkcji",'3',"youtube",["Dziedzina funkcji liczbowej","Zbiór wartości funkcji liczbowej. Najmniejsza i największa wartość funkcji"]],
["https://www.youtube.com/embed/2uq1GAgfY1Y",["film-podstawa1","film-rozszerzenie1"],"Odczytywanie dziedziny z wykresu funkcji LEKCJE Z FSOREM #31",'3',"youtube",["Dziedzina funkcji liczbowej"]],
["https://www.youtube.com/embed/yyrF7aE5Kx0",["film-podstawa1","film-rozszerzenie1"],"Wyznaczanie dziedziny na podstawie wzoru funkcji LEKCJE Z FSOREM #32",'3',"youtube",["Dziedzina funkcji liczbowej"]],
["https://www.youtube.com/embed/H0hVYA73E1g",["film-podstawa1","film-rozszerzenie1"],"JAK WYZNACZYĆ ZBIÓR WARTOŚCI FUNKCJI [#28]",'3',"youtube",["Zbiór wartości funkcji liczbowej. Najmniejsza i największa wartość funkcji"]],
["https://www.youtube.com/embed/ynfC7LkJHE8",["film-podstawa1","film-rozszerzenie1"],"Zbiór wartości funkcji liczbowej LEKCJE Z FSOREM #32",'3',"youtube",["Zbiór wartości funkcji liczbowej. Najmniejsza i największa wartość funkcji"]],
["https://www.youtube.com/embed/U4xtSyfkT_o",["film-podstawa1","film-rozszerzenie1"],"Czym jest dziedzina i zbiór wartości funkcji? Czym jest w ogóle funkcja?",'3',"youtube",["Dziedzina funkcji liczbowej","Zbiór wartości funkcji liczbowej. Najmniejsza i największa wartość funkcji"]],
["https://www.youtube.com/embed/wWDdh1nNoyk",["film-podstawa1","film-rozszerzenie1"],"Najmniejsza i największa wartość funkcji LEKCJE Z FSOREM #33",'3',"youtube",["Zbiór wartości funkcji liczbowej. Najmniejsza i największa wartość funkcji"]],
["https://www.youtube.com/embed/YZU_Y5SWgBg",["film-podstawa1","film-rozszerzenie1"],"MIEJSCE ZEROWE FUNKCJI [#29]",'3',"youtube",["Miejsce zerowe funkcji"]],
["https://www.youtube.com/embed/h8vC-Bkr368",["film-podstawa1","film-rozszerzenie1"],"Miejsce zerowe funkcji, wartości dodatnie i ujemne",'3',"youtube",["Miejsce zerowe funkcji"]],
["https://www.youtube.com/embed/o4iYN7ekEEQ",["film-podstawa1","film-rozszerzenie1"],"Miejsce zerowe funkcji #3 [ Własność funkcji ]",'3',"youtube",["Miejsce zerowe funkcji"]],
["https://www.youtube.com/embed/54woS0NgRS0",["film-rozszerzenie1"],"FUNKCJE RÓWNE [#30]",'3',"youtube",["Funkcje równe"]],
["https://www.youtube.com/embed/cKXVyrCjOWg",["film-rozszerzenie1"],"Funkcje równe LEKCJE Z FSOREM #35 ROZSZERZENIE",'3',"youtube",["Funkcje równe"]],
["https://www.youtube.com/embed/7VI2ZTZJkg8",["film-podstawa1","film-rozszerzenie1"],"MONOTONICZNOŚĆ FUNKCJI [#31]",'3',"youtube",["Monotoniczność funkcji"]],
["https://www.youtube.com/embed/S15hChUxw18",["film-podstawa1","film-rozszerzenie1"],"Liceum. Klasa I. Monotoniczność funkcji",'3',"youtube",["Monotoniczność funkcji"]],
["https://www.youtube.com/embed/R4Ix5oLTjG8",["film-podstawa1","film-rozszerzenie1"],"FUNKCJE RÓŻNOWARTOŚCIOWE [#32]",'3',"youtube",["Funkcje różnowartościowe"]],
["https://www.youtube.com/embed/-gjuSX6N7t8",["film-podstawa1","film-rozszerzenie1"],"Liceum. Klasa I. Funkcje różnowartościowe",'3',"youtube",["Funkcje różnowartościowe"]],
["https://www.youtube.com/embed/LK9rnClslKY",["film-rozszerzenie1"],"FUNKCJA PARZYSTA I NIEPARZYSTA [#33]",'3',"youtube",["Funkcje różnowartościowe"]],
["https://www.youtube.com/embed/UNOJDN8VT6k",["film-rozszerzenie1"],"Liceum. Klasa I. Funkcja parzysta i nieparzysta",'3',"youtube",["Funkcje różnowartościowe"]],
["https://www.youtube.com/embed/sxI58fIUI4g",["film-podstawa1"],"ODCZYTYWANIE WŁASNOŚCI FUNKCJI [#34]",'3',"youtube",["Odczytywanie własności funkcji o zadanych własnościach."]],
["https://www.youtube.com/embed/sxI58fIUI4g",["film-rozszerzenie1"],"ODCZYTYWANIE WŁASNOŚCI FUNKCJI [#34]",'3',"youtube",["Odczytywanie własności funkcji na podstawie jej wykresu. Szkicowanie wykresów funkcji o zadanych własnościach"]],
["https://www.youtube.com/embed/DjWwDQZbfk0",["film-rozszerzenie1"],"JAK SZKICOWAĆ WYKRES FUNKCJI? [#26]",'3',"youtube",["Odczytywanie własności funkcji na podstawie jej wykresu. Szkicowanie wykresów funkcji o zadanych własnościach"]],
["https://www.youtube.com/embed/URIQNSYSzc4",["film-rozszerzenie1"],"Wykres funkcji - rysowanie #1",'3',"youtube",["Odczytywanie własności funkcji na podstawie jej wykresu. Szkicowanie wykresów funkcji o zadanych własnościach"]],
["https://www.youtube.com/embed/WxV-uymfqbs",["film-rozszerzenie1"],"Wykres funkcji - rysowanie #2",'3',"youtube",["Odczytywanie własności funkcji na podstawie jej wykresu. Szkicowanie wykresów funkcji o zadanych własnościach"]],
["https://www.youtube.com/embed/RqyH_N7sUYA",["film-podstawa1"],"Własności funkcji #1 - odczytywanie z wykresu",'3',"youtube",["Odczytywanie własności funkcji na podstawie jej wykresu."]],
["https://www.youtube.com/embed/RqyH_N7sUYA",["film-rozszerzenie1"],"Własności funkcji #1 - odczytywanie z wykresu",'3',"youtube",["Odczytywanie własności funkcji na podstawie jej wykresu. Szkicowanie wykresów funkcji o zadanych własnościach"]],
["https://www.youtube.com/embed/72SWOd-Vnk4",["film-podstawa1","film-rozszerzenie1"],"Zastosowanie funkcji w życiu codziennym - temperatura #3 [ Funkcje ]",'3',"youtube",["Zastosowanie wiadomości o funkcjach do opisywania, interpretowania i przetwarzania informacji wyrażonych w postaci wykresu funkcji"]],
["https://www.youtube.com/embed/hjUeZEcwj2E",["film-podstawa1","film-rozszerzenie1"],"Zastosowanie funkcji w życiu codziennym - prędkość, droga i czas #4 [ Funkcje ]",'3',"youtube",["Zastosowanie wiadomości o funkcjach do opisywania, interpretowania i przetwarzania informacji wyrażonych w postaci wykresu funkcji"]],
["https://www.youtube.com/embed/6ilAjoAp-0M",["film-podstawa1","film-rozszerzenie1"],"Zastosowanie funkcji w życiu codziennym - gospodarka  #5 [ Funkcje ]",'3',"youtube",["Zastosowanie wiadomości o funkcjach do opisywania, interpretowania i przetwarzania informacji wyrażonych w postaci wykresu funkcji"]],
["https://www.youtube.com/embed/2XoKQM_pLf8",["film-podstawa1","film-rozszerzenie1"],"PROPORCJONALNOŚĆ PROSTA [#35]",'4',"youtube",["Proporcjonalność prosta"]],
["https://www.youtube.com/embed/0EhXqrzL9TU",["film-podstawa1","film-rozszerzenie1"],"wielkości wprost i odwrotnie proporcjonalne",'4',"youtube",["Proporcjonalność prosta"]],
["https://www.youtube.com/embed/kFdL5cpup04",["film-podstawa1","film-rozszerzenie1"],"Proporcjonalność prosta #1 [ Funkcja liniowa ]",'4',"youtube",["Proporcjonalność prosta"]],
["https://www.youtube.com/embed/pBqkCRu91UE",["film-podstawa1","film-rozszerzenie1"],"FUNKCJA LINIOWA - WYKRES I MIEJSCE ZEROWE [#36]",'4',"youtube",["Funkcja liniowa. Wykres i miejsce zerowe funkcji liniowej"]],
["https://www.youtube.com/embed/YZvkJd3WSjk",["film-podstawa1","film-rozszerzenie1"],"Zadania maturalne - funkcja liniowa.",'4',"youtube",["Funkcja liniowa. Wykres i miejsce zerowe funkcji liniowej"]],
["https://www.youtube.com/embed/gCsVjSYq3O4",["film-podstawa1","film-rozszerzenie1"],"Liceum. Klasa II. Funkcja liniowa. Wykres funkcji liniowej",'4',"youtube",["Funkcja liniowa. Wykres i miejsce zerowe funkcji liniowej"]],
["https://www.youtube.com/embed/LdEqRL__k6g",["film-podstawa1","film-rozszerzenie1"],"Funkcja liniowa - wprowadzenie #2 [ Funkcja liniowa ]",'4',"youtube",["Funkcja liniowa. Wykres i miejsce zerowe funkcji liniowej"]],
["https://www.youtube.com/embed/pnxtKkI7ppw",["film-podstawa1","film-rozszerzenie1"],"Funkcja liniowa podstawowe informacje LEKCJE Z FSOREM #38",'4',"youtube",["Funkcja liniowa. Wykres i miejsce zerowe funkcji liniowej"]],
["https://www.youtube.com/embed/BSkDKWhUqRo",["film-podstawa1","film-rozszerzenie1"],"WSPÓŁCZYNNIK KIERUNKOWY - FUNKCJA LINIOWA [#37]",'4',"youtube",["Znaczenie współczynnika kierunkowego we wzorze funkcji liniowej"]],
["https://www.youtube.com/embed/S7l_CcWWtgE",["film-podstawa1","film-rozszerzenie1"],"Współczynnik funkcji liniowej  y = ax + b #3 [ Funkcja liniowa ]",'4',"youtube",["Znaczenie współczynnika kierunkowego we wzorze funkcji liniowej"]],
["https://www.youtube.com/embed/PuQOC5rR3KE",["film-podstawa1","film-rozszerzenie1"],"Matura 2020 zadanie 7. Znalezienie współczynnika kierunkowego",'4',"youtube",["Znaczenie współczynnika kierunkowego we wzorze funkcji liniowej"]],
["https://www.youtube.com/embed/Y38AoUwFepw",["film-podstawa1","film-rozszerzenie1"],"Znaczenie współczynników we wzorze funkcji liniowej",'4',"youtube",["Znaczenie współczynnika kierunkowego we wzorze funkcji liniowej"]],
["https://www.youtube.com/embed/2QGnzvrbSYg",["film-podstawa1","film-rozszerzenie1"],"FUNKCJA LINIOWA - WŁASNOŚCI [#38]",'4',"youtube",["Własności funkcji liniowej - zadania różne"]],
["https://www.youtube.com/embed/NddBd7Sn1JQ",["film-podstawa1","film-rozszerzenie1"],"Funkcja liniowa własności - część 1",'4',"youtube",["Własności funkcji liniowej - zadania różne"]],
["https://www.youtube.com/embed/ceP8WCeHpQk",["film-podstawa1","film-rozszerzenie1"],"Funkcja liniowa własności - część 2",'4',"youtube",["Własności funkcji liniowej - zadania różne"]],
["https://www.youtube.com/embed/jQcm74HIesc",["film-podstawa1","film-rozszerzenie1"],"Funkcja liniowa podstawowe zadania LEKCJE Z FSOREM #39",'4',"youtube",["Własności funkcji liniowej - zadania różne"]],
["https://www.youtube.com/embed/IOkcKLGpAGE",["film-podstawa1","film-rozszerzenie1"],"ZASTOSOWANIE FUNKCJI LINIOWEJ [#39]",'4',"youtube",["Zastosowanie własności funkcji liniowej w zadaniach praktycznych"]],
["https://www.youtube.com/embed/QikFSnIAr54",["film-rozszerzenie1"],"WYKRESY WYBRANYCH FUNKCJI SIGNUM, MAKSIMUM I INNYCH [#40]",'4',"youtube",["Wykresy wybranych funkcji"]],
["https://www.youtube.com/embed/dDxdyB9bgFM",["film-rozszerzenie2"],"Nierówności z wartością bezwzględną #1 - podstawy",'2',"youtube",["Nierówności z wartością bezwzględną"]], 
["https://www.youtube.com/embed/_toUaYoZ6do",["film-rozszerzenie2"],"Nierówności z wartością bezwzględną #2",'2',"youtube",["Nierówności z wartością bezwzględną"]], 
["https://www.youtube.com/embed/UBqWHi5p8IQ",["film-rozszerzenie2"],"Nierówności z wartością bezwzględną - rozszerzenie",'2',"youtube",["Nierówności z wartością bezwzględną"]], 
["https://www.youtube.com/embed/tIQ3q_oB-3A",["film-rozszerzenie2"],"Nierówności z wartością bezwzględną - metoda algebraiczna #4 [ Wartość bezwzględna ]",'2',"youtube",["Nierówności z wartością bezwzględną"]], 
["https://www.youtube.com/embed/cPq-9EyJBMs",["film-rozszerzenie2"],"Liceum. Klasa II. Funkcja liniowa. Nierówności z wartością bezwzględną",'2',"youtube",["Nierówności z wartością bezwzględną"]], 
["https://www.youtube.com/embed/EBlbgeaEzjo",["film-rozszerzenie2"],"Równania i nierówności z wartością bezwzględną MATURA KURS ROZSZERZENIE Liczby rzeczywiste cz.2",'2',"youtube",["Nierówności z wartością bezwzględną"]], 
["https://www.youtube.com/embed/4n0w5A-474A",["film-rozszerzenie2"],"Równania i nierówności z wartością bezwzględną KURS MATURA PODSTAWA Równania i nierówności cz.2",'2',"youtube",["Nierówności z wartością bezwzględną"]], 
["https://www.youtube.com/embed/ycRaxHIuBMo",["film-rozszerzenie2"],"RÓWNANIA LINIOWE Z PARAMETREM",'2',"youtube",["Równania liniowe z parametrem"]], 
["https://www.youtube.com/embed/cxv5Kf2J1X8",["film-rozszerzenie2"],"Liceum. Klasa II. Funkcja liniowa. Równania i nierówności liniowe",'2',"youtube",["Równania liniowe z parametrem"]], 
["https://www.youtube.com/embed/ycRaxHIuBMo",["film-rozszerzenie2"],"RÓWNANIA LINIOWE Z PARAMETREM",'2',"youtube",["Równania liniowe z parametrem","Nierówności liniowe z parametrem"]], 
["https://www.youtube.com/embed/YMPX9DZYurY",["film-rozszerzenie2"],"Bezwzględne równanie z parametrem MATURA 2022 KURS ROZSZERZENIE Liczby rzeczywiste cz.3",'2',"youtube",["Równania liniowe z parametrem"]], 
["https://www.youtube.com/embed/6Fy6uYq__Fw",["film-rozszerzenie2"],"Funkcja liniowa na poziomie rozszerzonym",'2',"youtube",["Równania liniowe z parametrem"]], 
["https://www.youtube.com/embed/ycRaxHIuBMo",["film-rozszerzenie2"],"RÓWNANIA LINIOWE Z PARAMETREM",'2',"youtube",["Nierówności liniowe z parametrem"]],
["https://www.youtube.com/embed/zcbL65jMctA",["film-rozszerzenie2"],"Liceum. Klasa II. Funkcja liniowa. Układ równań z dwiema niewiadomymi z parametrem",'2',"youtube",["Układy równań pierwszego stopnia z dwiema niewiadomymi z parametrem"]],
["https://www.youtube.com/embed/ZHfNEkBcmPA",["film-rozszerzenie2"],"Układy równań - metoda podstawiania",'2',"youtube",["Układy równań pierwszego stopnia z dwiema niewiadomymi z parametrem"]],
["https://www.youtube.com/embed/sjQkMGTJeuQ",["film-rozszerzenie2"],"Układy równań metoda przeciwnych współczynników",'2',"youtube",["Układy równań pierwszego stopnia z dwiema niewiadomymi z parametrem"]], 
["https://www.youtube.com/embed/-12p6LMh9dQ",["film-rozszerzenie2"],"Układy równań pierwszego stopnia z dwiema niewiadomymi LEKCJE Z FSOREM",'2',"youtube",["Układy równań pierwszego stopnia z dwiema niewiadomymi z parametrem"]],
["https://www.youtube.com/embed/8EAMk8PUfrU",["film-podstawa2","film-rozszerzenie2"],"Funkcja kwadratowa #1 - postać ogólna i kanoniczna, obliczanie delty",'3',"youtube",["Przypomnienie wiadomości o funkcji kwadratowej z klasy 1.","Związek między wzorem funkcji kwadratowej w postaci ogólnej, a wzorem funkcji kwadratowej w postaci kanonicznej"]], 
["https://www.youtube.com/embed/cUwhdXz-rzE",["film-podstawa2","film-rozszerzenie2"],"Liceum. Klasa II. Funkcja kwadratowa. Wstęp do funkcji kwadratowej",'3',"youtube",["Przypomnienie wiadomości o funkcji kwadratowej z klasy 1."]], 
["https://www.youtube.com/embed/z26ShaBSpIs",["film-podstawa2","film-rozszerzenie2"],"Co to funkcja kwadratowa? odc.1 Wprowadzenie (Udostępnij na Grupce Klasowej)",'3',"youtube",["Przypomnienie wiadomości o funkcji kwadratowej z klasy 1."]], 
["https://www.youtube.com/embed/w2wk746ce0Q",["film-podstawa2","film-rozszerzenie2"],"Zamiana postaci kanonicznej na ogólną i odwrotnie #7 [ Funkcja kwadratowa - postać ogólna i kanonicz",'3',"youtube",["Związek między wzorem funkcji kwadratowej w postaci ogólnej, a wzorem funkcji kwadratowej w postaci kanonicznej"]], 
["https://www.youtube.com/embed/pSfm5R_sAt4",["film-podstawa2","film-rozszerzenie2"],"Liceum. Klasa II. Funkcja kwadratowa. Postać ogólna a kanoniczna funkcji kwadratowej",'3',"youtube",["Związek między wzorem funkcji kwadratowej w postaci ogólnej, a wzorem funkcji kwadratowej w postaci kanonicznej"]], 
["https://www.youtube.com/embed/hgcQqvS5N5M",["film-podstawa2","film-rozszerzenie2"],"Co to funkcja kwadratowa? odc.4 Zadania Postać Kanoniczna. (Udostępnij na Grupce Klasowej)",'3',"youtube",["Związek między wzorem funkcji kwadratowej w postaci ogólnej, a wzorem funkcji kwadratowej w postaci kanonicznej"]],  
["https://www.youtube.com/embed/wzz-Io-xVt4",["film-podstawa2","film-rozszerzenie2"],"Co to FUNKCJA KWADRATOWA W POSTACI OGÓLNEJ I KANONICZNEJ",'3',"youtube",["Związek między wzorem funkcji kwadratowej w postaci ogólnej, a wzorem funkcji kwadratowej w postaci kanonicznej"]],
["https://www.youtube.com/embed/S_IeVQxw698",["film-podstawa1", "film-rozszerzenie1"],"JAK ROZWĄZAĆ UKŁAD RÓWNAŃ [#41]",'5',"youtube",["Równania pierwszego stopnia z dwiema niewiadomymi"]],
["https://www.youtube.com/embed/YATtPZN4RM8",["film-podstawa1", "film-rozszerzenie1"],"Układy równań - przykłady z wzorami skróconego mnożenia",'5',"youtube",["Równania pierwszego stopnia z dwiema niewiadomymi"]],
["https://www.youtube.com/embed/-12p6LMh9dQ",["film-podstawa1", "film-rozszerzenie1"],"Układy równań pierwszego stopnia z dwiema niewiadomymi LEKCJE Z FSOREM",'5',"youtube",["Równania pierwszego stopnia z dwiema niewiadomymi"]],
["https://www.youtube.com/embed/n74BQHhpyIg",["film-podstawa1", "film-rozszerzenie1"],"JAK ROZWĄZAĆ UKŁAD RÓWNAŃ (metoda graficzna) [#42]",'5',"youtube",["Układy równań pierwszego stopnia z dwiema niewiadomymi. Graficzne rozwiązywanie układów równań"]],
["https://www.youtube.com/embed/oG9Ees3yyTs",["film-podstawa1", "film-rozszerzenie1"],"Interpretacja geometryczna układu równań liniowych",'5',"youtube",["Układy równań pierwszego stopnia z dwiema niewiadomymi. Graficzne rozwiązywanie układów równań"]],
["https://www.youtube.com/embed/yyGY84k6zvI",["film-podstawa1", "film-rozszerzenie1"],"Rozwiązywanie układów równań metodą graficzną #2 [ Układy równań - metoda graficzna ]",'5',"youtube",["Układy równań pierwszego stopnia z dwiema niewiadomymi. Graficzne rozwiązywanie układów równań"]],
["https://www.youtube.com/embed/Z1qmBcqCROQ",["film-podstawa1", "film-rozszerzenie1"],"Układy równań liniowych i interpretacja geometryczna MATURA PODSTAWA równania i nierówności cz.2",'5',"youtube",["Układy równań pierwszego stopnia z dwiema niewiadomymi. Graficzne rozwiązywanie układów równań"]],
["https://www.youtube.com/embed/ECmK1tGRzV8",["film-podstawa1", "film-rozszerzenie1"],"JAK ROZWIĄZAĆ UKŁAD RÓWNAŃ? (metoda podstawiania) [#43]",'5',"youtube",["Rozwiązywanie układów równań pierwszego stopnia z dwiema niewiadomymi metodą podstawiania"]],
["https://www.youtube.com/embed/ZHfNEkBcmPA",["film-podstawa1", "film-rozszerzenie1"],"Układy równań - metoda podstawiania",'5',"youtube",["Rozwiązywanie układów równań pierwszego stopnia z dwiema niewiadomymi metodą podstawiania"]],
["https://www.youtube.com/embed/3bk2fdNZmB8",["film-podstawa1", "film-rozszerzenie1"],"Układy równań - metoda podstawiania - poziom 2",'5',"youtube",["Rozwiązywanie układów równań pierwszego stopnia z dwiema niewiadomymi metodą podstawiania"]],
["https://www.youtube.com/embed/TTWaWRxLW5k",["film-podstawa1", "film-rozszerzenie1"],"Rozwiązywanie układów równań metodą podstawiania #3 [ Układy równań ]",'5',"youtube",["Rozwiązywanie układów równań pierwszego stopnia z dwiema niewiadomymi metodą podstawiania"]],
["https://www.youtube.com/embed/_F-5S1UMib8",["film-podstawa1", "film-rozszerzenie1"],"Metoda podstawiania - zadania #4 [ Układy równań ]",'5',"youtube",["Rozwiązywanie układów równań pierwszego stopnia z dwiema niewiadomymi metodą podstawiania"]],
["https://www.youtube.com/embed/e_r5_Zj7OlM",["film-podstawa1", "film-rozszerzenie1"],"JAK ROZWIĄZAĆ UKŁAD RÓWNAŃ? (metoda przeciwnych współczynników) [#44]",'5',"youtube",["Rozwiązywanie układów równań pierwszego stopnia z dwiema niewiadomymi metodą przeciwnych współczynników"]],
["https://www.youtube.com/embed/sjQkMGTJeuQ",["film-podstawa1", "film-rozszerzenie1"],"Układy równań metoda przeciwnych współczynników",'5',"youtube",["Rozwiązywanie układów równań pierwszego stopnia z dwiema niewiadomymi metodą przeciwnych współczynników"]],
["https://www.youtube.com/embed/wsiQtSNwvbk",["film-podstawa1", "film-rozszerzenie1"],"Metoda przeciwnych współczynników - zadania #6 [ Układy równań ]",'5',"youtube",["Rozwiązywanie układów równań pierwszego stopnia z dwiema niewiadomymi metodą przeciwnych współczynników"]],
["https://www.youtube.com/embed/lXO51O-xVME",["film-podstawa1", "film-rozszerzenie1"],"Układy równań - zadania tekstowe - liczba dwucyfrowa/trzycyfrowa",'5',"youtube",["Zastosowanie układów równań do rozwiązywania zadań"]],
["https://www.youtube.com/embed/wb4qbSDkk9E",["film-podstawa1", "film-rozszerzenie1"],"Układy równań - zadania tekstowe #1 [ Układy równań - zadania ]",'5',"youtube",["Zastosowanie układów równań do rozwiązywania zadań"]],
["https://www.youtube.com/embed/xYsu9ikqBk0",["film-podstawa1", "film-rozszerzenie1"],"Zadania o liczbach #2 [ Układy równań - zadania ]",'5',"youtube",["Zastosowanie układów równań do rozwiązywania zadań"]],
["https://www.youtube.com/embed/icpyz8fFFRs",["film-podstawa1", "film-rozszerzenie1"],"Zadania o wieku ludzi #3 [ Układy równań - zadania ]",'5',"youtube",["Zastosowanie układów równań do rozwiązywania zadań"]],
["https://www.youtube.com/embed/PtzAnTC58DM",["film-podstawa1", "film-rozszerzenie1"],"Zadania geometryczne #4 [ Układy równań - zadania ]",'5',"youtube",["Zastosowanie układów równań do rozwiązywania zadań"]],
["https://www.youtube.com/embed/Z1R0QDBGsgU",["film-podstawa1", "film-rozszerzenie1"],"Zadania procentowe #5 [ Układy równań - zadania ]",'5',"youtube",["Zastosowanie układów równań do rozwiązywania zadań"]],
["https://www.youtube.com/embed/3Y5h61EYVs8",["film-podstawa1", "film-rozszerzenie1"],"Zadania wykorzystujące układy równań #6 [ Układy równań - zadania ]",'5',"youtube",["Zastosowanie układów równań do rozwiązywania zadań"]],
["https://www.youtube.com/embed/ZYyebgrrUno",["film-podstawa1","film-rozszerzenie1"],"FUNKCJA KWADRATOWA [#45]",'6',"youtube",["Funkcja kwadratowa"]],
["https://www.youtube.com/embed/8EAMk8PUfrU",["film-podstawa1","film-rozszerzenie1"],"Funkcja kwadratowa #1 - postać ogólna i kanoniczna, obliczanie delty",'6',"youtube",["Funkcja kwadratowa"]],
["https://www.youtube.com/embed/lBnepB1Pnoo",["film-podstawa1","film-rozszerzenie1"],"Funkcja kwadratowa #2 - wierzchołek paraboli, wartość największa, oś symetrii, zbiór wartości",'6',"youtube",["Funkcja kwadratowa"]],
["https://www.youtube.com/embed/P2uuU_k0JxI",["film-podstawa1","film-rozszerzenie1"]," Wykres i własności funkcji x do kwadratu #1 [ Funkcja kwadratowa - postać ogólna i kanoniczna ]",'6',"youtube",["Funkcja kwadratowa"]],
["https://www.youtube.com/embed/MlKVKOI4IEw",["film-podstawa1","film-rozszerzenie1"]," Wykres i własności funkcji minus x do kwadratu #2 [ Funkcja kwadratowa - postać ogólna i kanoniczna ]",'6',"youtube",["Funkcja kwadratowa"]],
["https://www.youtube.com/embed/8N9U7DB0XQc",["film-podstawa1","film-rozszerzenie1"],"Postać kanoniczna - wprowadzenie #4 [ Funkcja kwadratowa - postać ogólna i kanoniczna ]",'6',"youtube",["Funkcja kwadratowa"]],
["https://www.youtube.com/embed/aR_rOdHbqGE",["film-podstawa1","film-rozszerzenie1"],"Postać kanoniczna - własności funkcji #5 [ Funkcja kwadratowa - postać ogólna i kanoniczna ]",'6',"youtube",["Funkcja kwadratowa"]],
["https://www.youtube.com/embed/cUwhdXz-rzE",["film-podstawa1","film-rozszerzenie1"],"Liceum. Klasa II. Funkcja kwadratowa. Wstęp do funkcji kwadratowej",'6',"youtube",["Funkcja kwadratowa"]],
["https://www.youtube.com/embed/VKsaJ73TC1I",["film-podstawa1","film-rozszerzenie1"],"Liceum. Klasa II. Funkcja kwadratowa. Postać kanoniczna funkcji kwadratowej",'6',"youtube",["Funkcja kwadratowa"]],
["https://www.youtube.com/embed/z26ShaBSpIs",["film-podstawa1","film-rozszerzenie1"],"Co to funkcja kwadratowa? odc.1 Wprowadzenie (Udostępnij na Grupce Klasowej)",'6',"youtube",["Funkcja kwadratowa"]],
["https://www.youtube.com/embed/2D-s3h2o1n8",["film-podstawa1","film-rozszerzenie1"],"MATURA MATEMATYKA Funkcja kwadratowa Teoria PEWNIAK",'6',"youtube",["Funkcja kwadratowa"]],
["https://www.youtube.com/embed/zpSo9Lug4fs",["film-podstawa1","film-rozszerzenie1"], "Funkcja kwadratowa",'6',"youtube",["Funkcja kwadratowa"]],
["https://www.youtube.com/embed/hzsGT-H5l28",["film-podstawa1","film-rozszerzenie1"],"Funkcja kwadratowa - zadania #1",'6',"youtube",["Funkcja kwadratowa - zastosowania"]],
["https://www.youtube.com/embed/1I1B5IAPoi0",["film-podstawa1","film-rozszerzenie1"],"Zadanie maturalne - funkcja kwadratowa.",'6',"youtube",["Funkcja kwadratowa - zastosowania"]],
["https://www.youtube.com/embed/EYTXSmqR1GI",["film-podstawa1","film-rozszerzenie1"],"eZadanie maturalne - funkcja kwadratowa.",'6',"youtube",["Funkcja kwadratowa - zastosowania"]],
["https://www.youtube.com/embed/d-a1ji3KATM",["film-podstawa1","film-rozszerzenie1"],"Postać kanoniczna - zadania #6 [ Funkcja kwadratowa - postać ogólna i kanoniczna]",'6',"youtube",["Funkcja kwadratowa - zastosowania"]],
["https://www.youtube.com/embed/8UnJsmkbQhQ",["film-podstawa1","film-rozszerzenie1"],"PROPORCJONALNOŚĆ ODWROTNA [#46]",'6',"youtube",["Proporcjonalność odwrotna"]],
["https://www.youtube.com/embed/eRFesoidVbk",["film-podstawa1","film-rozszerzenie1"],"Proporcja odwrotna #3 [ Proporcje ]",'6',"youtube",["Proporcjonalność odwrotna"]],
["https://www.youtube.com/embed/vT2DSNsvLCs",["film-podstawa1","film-rozszerzenie1"],"FUNKCJA WYKŁADNICZA [#47]",'6',"youtube",["Funkcja wykładnicza"]],
["https://www.youtube.com/embed/-U6xBu8PfZY",["film-podstawa1","film-rozszerzenie1"],"Zadanie maturalne - wartości funkcji wykładniczej.",'6',"youtube",["Funkcja wykładnicza"]],
["https://www.youtube.com/embed/zOxq_iNX7ao",["film-rozszerzenie1"],"Funkcja wykładnicza na poziomie rozszerzonym",'6',"youtube",["Funkcja wykładnicza"]],
["https://www.youtube.com/embed/TA1sBb5tCHE",["film-podstawa1","film-rozszerzenie1"],"FUNKCJA LOGARYTMICZNA - co to jest?",'6',"youtube",["Funkcja logarytmiczna"]],
["https://www.youtube.com/embed/zb5X7xqpydY",["film-rozszerzenie1"],"Logarytmy, funkcja wykładnicza i logarytmiczna - A co było na maturze rozszerzonej?",'6',"youtube",["Funkcja logarytmiczna"]],
["https://www.youtube.com/embed/xnNHHTu9EVg",["film-podstawa1","film-rozszerzenie1"],"GEOMETRIA - WSTĘP [#49]",'7',"youtube",["Punkt, prosta, odcinek, półprosta, kąt, figura wypukła, figura ograniczona"]],
["https://www.youtube.com/embed/75Ci9E3vHv8",["film-podstawa1","film-rozszerzenie1"],"Punkt, prosta, odcinek, półprosta, kąt, figura wypukła, figura ograniczona - definicje, przykłady",'7',"youtube",["Punkt, prosta, odcinek, półprosta, kąt, figura wypukła, figura ograniczona"]],
["https://www.youtube.com/embed/_bYXHZUcpkE",["film-podstawa1","film-rozszerzenie1"],"Punkt, odcinek, prosta, półprosta #1 [ Proste i odcinki ]",'7',"youtube",["Punkt, prosta, odcinek, półprosta, kąt, figura wypukła, figura ograniczona"]],
["https://www.youtube.com/embed/XF0liQiZtWo",["film-podstawa1","film-rozszerzenie1"],"Pojęcia w geometrii #1 [ Wstęp do geometrii ]",'7',"youtube",["Punkt, prosta, odcinek, półprosta, kąt, figura wypukła, figura ograniczona"]],
["https://www.youtube.com/embed/xLq6KC55dSw",["film-podstawa1","film-rozszerzenie1"],"Liceum. Klasa I. Wstęp do geometrii",'7',"youtube",["Punkt, prosta, odcinek, półprosta, kąt, figura wypukła, figura ograniczona"]],
["https://www.youtube.com/embed/0E86jZhoAsY",["film-podstawa1","film-rozszerzenie1"],"Liceum. Klasa I. Proste i odcinki",'7',"youtube",["Wzajemne położenie prostych na płaszczyźnie, odległość punktu od prostej, odległość między prostymi równoległymi, symetralna odcinka, dwusieczna kąta"]],
["https://www.youtube.com/embed/8VnWxwCxVjI",["film-podstawa1","film-rozszerzenie1"],"POŁOŻENIE PROSTYCH NA PŁASZCZYŹNIE [#50]",'7',"youtube",["Wzajemne położenie prostych na płaszczyźnie, odległość punktu od prostej, odległość między prostymi równoległymi, symetralna odcinka, dwusieczna kąta"]],
["https://www.youtube.com/embed/cLrDkWZ64N8",["film-podstawa1","film-rozszerzenie1"],"Wzajemne położenie prostych na płaszczyźnie, symetralna, dwusieczna kąta - definicje, przykłady",'7',"youtube",["Wzajemne położenie prostych na płaszczyźnie, odległość punktu od prostej, odległość między prostymi równoległymi, symetralna odcinka, dwusieczna kąta"]],
["https://www.youtube.com/embed/KYhvhcW9M8g",["film-podstawa1","film-rozszerzenie1"],"Odległość punktu od prostej #5 [ Proste i odcinki ]",'7',"youtube",["Wzajemne położenie prostych na płaszczyźnie, odległość punktu od prostej, odległość między prostymi równoległymi, symetralna odcinka, dwusieczna kąta"]],
["https://www.youtube.com/embed/4HRorhGgvVg",["film-podstawa1","film-rozszerzenie1"],"Liceum. Klasa I. Proste i kąty",'7',"youtube",["Dwie proste przecięte trzecią prostą. Suma kątów w trójkącie", "Wielokąt. Wielokąt foremny. Suma kątów w trójkącie"]],
["https://www.youtube.com/embed/-JRIzwxajYQ",["film-podstawa1","film-rozszerzenie1"],"MIARY KĄTÓW MIĘDZY PROSTYMI PRZECIĘTYMI TRZECIĄ PROSTĄ [#51]",'7',"youtube",["Dwie proste przecięte trzecią prostą. Suma kątów w trójkącie"]],
["https://www.youtube.com/embed/pxz5zBHPXho",["film-podstawa1","film-rozszerzenie1"],"Dwie proste przecięte trzecią prostą, suma kątów w trójkącie - definicje, przykłady",'7',"youtube",["Dwie proste przecięte trzecią prostą. Suma kątów w trójkącie"]],
["https://www.youtube.com/embed/b8jLJ4y-_74",["film-podstawa1","film-rozszerzenie1"],"Proste równoległe przecięte trzecią prostą - kąty #3 [ Kąty powstałe w wyniku przecięcia prostych ]",'7',"youtube",["Dwie proste przecięte trzecią prostą. Suma kątów w trójkącie"]],
["https://www.youtube.com/embed/MoNAiOAUDtc",["film-podstawa1","film-rozszerzenie1"],"Liceum. Klasa I. Wstęp do geometrii 2",'7',"youtube",["Wielokąt. Wielokąt foremny. Suma kątów w wielokącie"]],
["https://www.youtube.com/embed/qdzYSaQhsQ0",["film-podstawa1","film-rozszerzenie1"],"WIELOKĄTY FOREMNE [#52]",'7',"youtube",["Wielokąt. Wielokąt foremny. Suma kątów w wielokącie"]],
["https://www.youtube.com/embed/T1JNutBGF88",["film-podstawa1","film-rozszerzenie1"],"kąt wewnętrzny wielokąta foremnego",'7',"youtube",["Wielokąt. Wielokąt foremny. Suma kątów w wielokącie"]],
["https://www.youtube.com/embed/2XkPXgkURXE",["film-podstawa1","film-rozszerzenie1"],"Wielokąty foremne #1 [ Wielokąty foremne ]",'7',"youtube",["Wielokąt. Wielokąt foremny. Suma kątów w wielokącie"]],
["https://www.youtube.com/embed/857XiKa5i1Q",["film-podstawa1","film-rozszerzenie1"],"Kąt wewnętrzny wielokąta foremnego #2 [ Wielokąty foremne ]",'7',"youtube",["Wielokąt. Wielokąt foremny. Suma kątów w wielokącie"]],
["https://www.youtube.com/embed/wG1yJ4dzmf4",["film-podstawa1","film-rozszerzenie1"],"Liczba przekątnych wielokąta foremnego #3 [ Wielokąty foremne ]",'7',"youtube",["Wielokąt. Wielokąt foremny. Suma kątów w wielokącie"]],
["https://www.youtube.com/embed/lKhqN840Rqo",["film-podstawa1","film-rozszerzenie1"],"TWIERDZENIE TALESA [#53]",'7',"youtube",["Twierdzenie Talesa"]],
["https://www.youtube.com/embed/gzCrBCUlrxE",["film-podstawa1","film-rozszerzenie1"],"Twierdzenie Talesa i twierdzenie odwrotne",'7',"youtube",["Twierdzenie Talesa"]],
["https://www.youtube.com/embed/4nas5h7A9u4",["film-podstawa1","film-rozszerzenie1"],"Twierdzenie Talesa #5 [ Podobieństwo trójkątów ]",'7',"youtube",["Twierdzenie Talesa"]],
["https://www.youtube.com/embed/c7mSym-BW1k",["film-podstawa1","film-rozszerzenie1"],"Liceum. Klasa I. Twierdzenie Talesa",'7',"youtube",["Twierdzenie Talesa"]],
["https://www.youtube.com/embed/YIs-uIaKvHQ",["film-podstawa1","film-rozszerzenie1"],"Twierdzenie Talesa Zupełnie od Zera (Udostępnij na Grupce Klasowej)",'7',"youtube",["Twierdzenie Talesa"]],
["https://www.youtube.com/embed/-yL-MbFcMaI",["film-podstawa1","film-rozszerzenie1"],"WŁASNOŚCI TRÓJKĄTÓW [#54]",'7',"youtube",["Podział trójkątów. Nierówność trójkąta. Odcinek łączący środki boków w trójkącie"]],
["https://www.youtube.com/embed/YkC9JZQgENk",["film-podstawa1","film-rozszerzenie1"]," Podział trójkątów ze względu na kąty i boki #2 [ Trójkąty - wprowadzenie ]",'7',"youtube",["Podział trójkątów. Nierówność trójkąta. Odcinek łączący środki boków w trójkącie"]],
["https://www.youtube.com/embed/O7luA3oiHA4",["film-podstawa1","film-rozszerzenie1"]," Liceum. Klasa I. Trójkąty",'7',"youtube",["Podział trójkątów. Nierówność trójkąta. Odcinek łączący środki boków w trójkącie"]],
["https://www.youtube.com/embed/ZoQjeTq6-jo",["film-podstawa1","film-rozszerzenie1"]," TWIERDZENIE PITAGORASA [#55]",'7',"youtube",["Twierdzenie Pitagorasa. Twierdzenie odwrotne do twierdzenia Pitagorasa"]],
["https://www.youtube.com/embed/_WAX_an-aC4",["film-podstawa1","film-rozszerzenie1"],"Twierdzenie Pitagorasa - od podstaw",'7',"youtube",["Twierdzenie Pitagorasa. Twierdzenie odwrotne do twierdzenia Pitagorasa"]],
["https://www.youtube.com/embed/Gl_ocz8jzqM",["film-podstawa1","film-rozszerzenie1"],"Twierdzenie Pitagorasa - wprowadzenie #1 [ Twierdzenie Pitagorasa ]",'7',"youtube",["Twierdzenie Pitagorasa. Twierdzenie odwrotne do twierdzenia Pitagorasa"]],
["https://www.youtube.com/embed/30OKS5t1xcc",["film-podstawa1","film-rozszerzenie1"],"Liceum. Klasa I. Twierdzenie Pitagorasa",'7',"youtube",["Twierdzenie Pitagorasa. Twierdzenie odwrotne do twierdzenia Pitagorasa"]],
["https://www.youtube.com/embed/9khlpVfa0Sc",["film-podstawa1","film-rozszerzenie1"]," Przydatny wzór odc. 1 - tw. Pitagorasa oraz zastosowania",'7',"youtube",["Twierdzenie Pitagorasa. Twierdzenie odwrotne do twierdzenia Pitagorasa"]],
["https://www.youtube.com/embed/X6m4VXQDlKk",["film-podstawa1","film-rozszerzenie1"]," Przydatny wzór odc. 2 - tw. Pitagorasa oraz zastosowania",'7',"youtube",["Twierdzenie Pitagorasa. Twierdzenie odwrotne do twierdzenia Pitagorasa"]],
["https://www.youtube.com/embed/VNZWKAXxuGc",["film-podstawa1","film-rozszerzenie1"],"WYSOKOŚCI I ŚRODKOWE W TRÓJKĄCIE [#56]",'7',"youtube",["Wysokości w trójkącie. Środkowe w trójkącie"]],
["https://www.youtube.com/embed/iobLCK3Oo9k",["film-podstawa1","film-rozszerzenie1"]," wysokość trójkąta równobocznego",'7',"youtube",["Wysokości w trójkącie. Środkowe w trójkącie"]],
["https://www.youtube.com/embed/kDltOagTCDo",["film-podstawa1","film-rozszerzenie1"],"Wysokość trójkąta #3 [ Trójkąty - wprowadzenie ]",'7',"youtube",["Wysokości w trójkącie. Środkowe w trójkącie"]],
["https://www.youtube.com/embed/IxkJHqWCTQI",["film-podstawa1","film-rozszerzenie1"],"Liceum. Klasa I. Wysokości i środkowe w trójkącie",'7',"youtube",["Wysokości w trójkącie. Środkowe w trójkącie"]],
["https://www.youtube.com/embed/hMw9lH-caUw",["film-podstawa1","film-rozszerzenie1"],"TRÓJKĄTY PRZYSTAJĄCE [#57]",'7',"youtube",["Przystawanie trójkątów"]],
["https://www.youtube.com/embed/wOmDdn9E4_g",["film-podstawa1","film-rozszerzenie1"],"Trójkąty przystające - cechy przystawania",'7',"youtube",["Przystawanie trójkątów"]],
["https://www.youtube.com/embed/CuWd9I26f5c",["film-podstawa1","film-rozszerzenie1"]," Przystawanie trójkątów #7 [ Trójkąty ]",'7',"youtube",["Przystawanie trójkątów"]],
["https://www.youtube.com/embed/EMkM89YXITk",["film-podstawa1","film-rozszerzenie1"],"Liceum. Klasa I. Przystawanie trójkątów",'7',"youtube",["Przystawanie trójkątów"]],
["https://www.youtube.com/embed/WW4jXZaAcfo",["film-podstawa1","film-rozszerzenie1"],"TRÓJKĄTY PODOBNE [#58]",'7',"youtube",["Podobieństwo trójkątów", "Podobieństwo trójkątów - zastosowanie w zadaniach"]],
["https://www.youtube.com/embed/rlZJuhtXqnI",["film-podstawa1","film-rozszerzenie1"],"Trójkąty podobne - matura 2015",'7',"youtube", ["Podobieństwo trójkątów", "Podobieństwo trójkątów - zastosowanie w zadaniach"]],
["https://www.youtube.com/embed/qXRxBWku2Fk",["film-podstawa1","film-rozszerzenie1"],"Trójkąty podobne w trójkątach #1 [ Podobieństwo trójkątów ]",'7',"youtube", ["Podobieństwo trójkątów", "Podobieństwo trójkątów - zastosowanie w zadaniach"]],
["https://www.youtube.com/embed/pUZMyjl34oA",["film-podstawa1","film-rozszerzenie1"]," Trójkąty podobne w czworokątach #2 [ Podobieństwo trójkątów ]",'7',"youtube", ["Podobieństwo trójkątów", "Podobieństwo trójkątów - zastosowanie w zadaniach"]],
["https://www.youtube.com/embed/nEcAi87Oi6A",["film-podstawa1","film-rozszerzenie1"],"Liceum. Klasa I. Podobieństwo trójkątów",'7',"youtube", ["Podobieństwo trójkątów", "Podobieństwo trójkątów - zastosowanie w zadaniach"]],
["https://www.youtube.com/embed/wQeAzgttOUM",["film-rozszerzenie1"],"WEKTORY NA PŁASZCZYŹNIE [#59]",'7',"youtube", ["Wektor na płaszczyźnie"]],
["https://www.youtube.com/embed/LqBrQp-f2I0",["film-rozszerzenie1"]," Wektory - Wprowadzenie Odc.1 (na szybko bo wychodzę za 5 min) (Udostępnij na Grupce Klasowej)",'7',"youtube", ["Wektor na płaszczyźnie"]],
["https://www.youtube.com/embed/9agT9Lu6pJQ",["film-rozszerzenie1"]," Liceum. Klasa I. Wektor w układzie współrzędnych",'7',"youtube", ["Wektor na płaszczyźnie"]],
["https://www.youtube.com/embed/aivTB9ly-tw",["film-podstawa1","film-rozszerzenie1"],"SINUS / COSINUS / TANGENS / COTANGENS - FUNKCJE TRYGONOMETRYCZNE [#60]","8","youtube",["Określenie sinusa, cosinusa, tangensa i cotangensa w trójkącie prostokątnym"]],
["https://www.youtube.com/embed/qX232RNzZ_M",["film-podstawa1","film-rozszerzenie1"],"Trygonometria kąta ostrego - część 1 - podstawy","8","youtube",["Określenie sinusa, cosinusa, tangensa i cotangensa w trójkącie prostokątnym"]],
["https://www.youtube.com/embed/tZk4LdG_1rU",["film-podstawa1","film-rozszerzenie1"],"Trygonometria kąta ostrego - część 2","8","youtube",["Określenie sinusa, cosinusa, tangensa i cotangensa w trójkącie prostokątnym"]],
["https://www.youtube.com/embed/lGcuKPtOTEk",["film-podstawa1","film-rozszerzenie1"],"Sinus, cosinus i tangens w trójkącie prostokątnym #1 [ Trygonometria ]","8","youtube",["Określenie sinusa, cosinusa, tangensa i cotangensa w trójkącie prostokątnym"]],
["https://www.youtube.com/embed/XYMK7H9712Q",["film-podstawa1","film-rozszerzenie1"],"Wyznaczanie boków trójkąta znając sinus, cosinus lub tangens #2 [ Trygonometria ]","8","youtube",["Określenie sinusa, cosinusa, tangensa i cotangensa w trójkącie prostokątnym"]],
["https://www.youtube.com/embed/TRNiRkB1llA",["film-podstawa1","film-rozszerzenie1"],"Korzystanie z tablic trygonometrycznych #3 [ Trygonometria ]","8","youtube",["Określenie sinusa, cosinusa, tangensa i cotangensa w trójkącie prostokątnym"]],
["https://www.youtube.com/embed/lsmzRf830zE",["film-podstawa1","film-rozszerzenie1"]," Liceum. Klasa I. Wstęp do trygonometrii","8","youtube",["Określenie sinusa, cosinusa, tangensa i cotangensa w trójkącie prostokątnym", "Wartości sinusa, cosinusa, tangensa i cotangensa kątów 30°, 45° i 60°"]],
["https://www.youtube.com/embed/fBptK4ev4ho",["film-podstawa1","film-rozszerzenie1"]," WARTOŚCI SINUSA / COSIUNA / TANGENSA / COTANGENSA DLA KĄTÓW 30°, 45°, 60° [#61]","8","youtube",["Wartości sinusa, cosinusa, tangensa i cotangensa kątów 30°, 45° i 60°"]],
["https://www.youtube.com/embed/_JhMCrCtw9M",["film-podstawa1","film-rozszerzenie1"],"Wartości sinusa, cosinusa, tangensa dla kątów 30 i 60 stopni #4 [ Trygonometria ]","8","youtube",["Wartości sinusa, cosinusa, tangensa i cotangensa kątów 30°, 45° i 60°"]],
["https://www.youtube.com/embed/9dIGRWSq6AM",["film-podstawa1","film-rozszerzenie1"],"Wartości sinusa, cosinusa, tangensa dla kątów 45 stopni #5 [ Trygonometria ]","8","youtube",["Wartości sinusa, cosinusa, tangensa i cotangensa kątów 30°, 45° i 60°"]],
["https://www.youtube.com/embed/1WSjWvdFCsk",["film-podstawa1","film-rozszerzenie1"],"ZALEŻNOŚCI MIĘDZY FUNKCJAMI TRYGONOMETRYCZNYMI [#62]","8","youtube",["Zależności między funkcjami trygonometrycznymi tego samego kąta ostrego"]],
["https://www.youtube.com/embed/zvZltxwb1hc",["film-podstawa1","film-rozszerzenie1"]," Trygonometria kąta ostrego - część 3","8","youtube",["Zależności między funkcjami trygonometrycznymi tego samego kąta ostrego"]],
["https://www.youtube.com/embed/S0nexv9bhKI",["film-podstawa1","film-rozszerzenie1"]," Trygonometria kąta ostrego - część 5","8","youtube",["Zależności między funkcjami trygonometrycznymi tego samego kąta ostrego"]],
["https://www.youtube.com/embed/qWv_tcmikcM",["film-podstawa1","film-rozszerzenie1"],"Funkcje Trygonometryczne Wstęp + Zadanie Maturalne (Udostępnij na Grupce Klasowej)","8","youtube",["Zależności między funkcjami trygonometrycznymi tego samego kąta ostrego"]],
["https://www.youtube.com/embed/X__SR4HHDuU",["film-podstawa1","film-rozszerzenie1"],"Trygonometria","8","youtube",["Zależności między funkcjami trygonometrycznymi tego samego kąta ostrego"]],
["https://www.youtube.com/embed/-U6xBu8PfZY",["film-podstawa4", "film-rozszerzenie4"],"Zadanie maturalne - wartości funkcji wykładniczej.",'1',"youtube",["Potęga o wykładniku rzeczywistym - powtórzenie"]],
["https://www.youtube.com/embed/Ubn1hMYpiCc",["film-podstawa4", "film-rozszerzenie4"],"Potęgi, logarytmy i funkcja wykładnicza",'1',"youtube",["Funkcja wykładnicza i jej właściwości","Przekształcenia wykresów funkcji wykładniczych"]],
["https://www.youtube.com/embed/zOxq_iNX7ao",["film-rozszerzenie4"],"Funkcja wykładnicza na poziomie rozszerzonym",'1',"youtube",["Funkcja wykładnicza i jej właściwości","Nierówności wykładnicze","Zastosowanie własności funkcji wykładniczej w zadaniach"]],
["https://www.youtube.com/embed/vT2DSNsvLCs",["film-podstawa4", "film-rozszerzenie4"],"FUNKCJA WYKŁADNICZA [#47]",'1',"youtube",["Funkcja wykładnicza i jej właściwości"]],
["https://www.youtube.com/embed/zzeQjqaoRME",["film-podstawa4", "film-rozszerzenie4"],"Działania na potęgach o wykładniku ujemnym #3 [ Notacja wykładnicza ]",'1',"youtube",["Potęga o wykładniku rzeczywistym - powtórzenie"]],
["https://www.youtube.com/embed/ZYyebgrrUno",["film-podstawa2","film-rozszerzenie2"],"FUNKCJA KWADRATOWA [#45]","3","youtube",["Przypomnienie wiadomości o funkcji kwadratowej z klasy 1."]],
["https://www.youtube.com/embed/P2uuU_k0JxI",["film-podstawa2","film-rozszerzenie2"]," Wykres i własności funkcji x do kwadratu #1 [ Funkcja kwadratowa - postać ogólna i kanoniczna ]","3","youtube",["Przypomnienie wiadomości o funkcji kwadratowej z klasy 1."]],
["https://www.youtube.com/embed/wzz-Io-xVt4",["film-podstawa2","film-rozszerzenie2"]," FUNKCJA KWADRATOWA W POSTACI OGÓLNEJ I KANONICZNEJ","3","youtube",["Związek między wzorem funkcji kwadratowej w postaci ogólnej, a wzorem funkcji kwadratowej w postaci kanonicznej"]],
["https://www.youtube.com/embed/8EAMk8PUfrU",["film-podstawa2","film-rozszerzenie2"],"Funkcja kwadratowa #1 - postać ogólna i kanoniczna, obliczanie delty","3","youtube",["Związek między wzorem funkcji kwadratowej w postaci ogólnej, a wzorem funkcji kwadratowej w postaci kanonicznej"]],
["https://www.youtube.com/embed/w2wk746ce0Q",["film-podstawa2","film-rozszerzenie2"],"Zamiana postaci kanonicznej na ogólną i odwrotnie #7 [ Funkcja kwadratowa - postać ogólna i kanoniczna]","3","youtube",["Związek między wzorem funkcji kwadratowej w postaci ogólnej, a wzorem funkcji kwadratowej w postaci kanonicznej"]],
["https://www.youtube.com/embed/pSfm5R_sAt4",["film-podstawa2","film-rozszerzenie2"],"Liceum. Klasa II. Funkcja kwadratowa. Postać ogólna a kanoniczna funkcji kwadratowej","3","youtube",["Związek między wzorem funkcji kwadratowej w postaci ogólnej, a wzorem funkcji kwadratowej w postaci kanonicznej"]],
["https://www.youtube.com/embed/03PqlV8gh6w",["film-podstawa2","film-rozszerzenie2"],"MIEJSCE ZEROWE FUNKCJI KWADRATOWEJ","3","youtube",["Miejsce zerowe funkcji kwadratowej. Wzór funkcji kwadratowej w postaci iloczynowej"]],
["https://www.youtube.com/embed/iN915GJTS-w",["film-podstawa2","film-rozszerzenie2"],"POSTAĆ ILOCZYNOWA FUNKCJI KWADRATOWEJ","3","youtube",["Miejsce zerowe funkcji kwadratowej. Wzór funkcji kwadratowej w postaci iloczynowej"]],
["https://www.youtube.com/embed/RqOk1zHjQjw",["film-podstawa2","film-rozszerzenie2"],"Postać iloczynowa funkcji kwadratowej.","3","youtube",["Miejsce zerowe funkcji kwadratowej. Wzór funkcji kwadratowej w postaci iloczynowej"]],
["https://www.youtube.com/embed/spKuvDAS9uQ",["film-podstawa2","film-rozszerzenie2"],"Liceum. Klasa II. Funkcja kwadratowa. Miejsca zerowe i postać iloczynowa funkcji kwadratowej","3","youtube",["Miejsce zerowe funkcji kwadratowej. Wzór funkcji kwadratowej w postaci iloczynowej"]],
["https://www.youtube.com/embed/RkmY_T3Ta9A",["film-podstawa2","film-rozszerzenie2"],"Postać iloczynowa #7 [ Równania kwadratowe i postać iloczynowa ]","3","youtube",["Miejsce zerowe funkcji kwadratowej. Wzór funkcji kwadratowej w postaci iloczynowej"]],
["https://www.youtube.com/embed/GB4tCEH-80M",["film-podstawa2","film-rozszerzenie2"],"Zamiana postaci ogólnej i kanonicznej na iloczynową #8 [ Równania kwadratowe i postać iloczynowa ]","3","youtube",["Miejsce zerowe funkcji kwadratowej. Wzór funkcji kwadratowej w postaci iloczynowej"]],
["https://www.youtube.com/embed/iVPi-9Uz7eE",["film-podstawa2","film-rozszerzenie2"],"JAK NASZKICOWAĆ WYKRES FUNKCJI KWADRATOWEJ - krok po kroku","3","youtube",["Szkicowanie wykresów funkcji kwadratowej. Odczytywanie własności funkcji kwadratowej na podstawie wykresu"]],
["https://www.youtube.com/embed/TuKQs5YOdbw",["film-podstawa2","film-rozszerzenie2"],"Liceum. Klasa II. Funkcja kwadratowa. Szkicowanie wykresów funkcji kwadratowej","3","youtube",["Szkicowanie wykresów funkcji kwadratowych. Odczytywanie własności funkcji kwadratowej na podstawie wykresu"]],
["https://www.youtube.com/embed/OPQ2SbYJp3E",["film-podstawa2","film-rozszerzenie2"],"JAK WYZNACZYĆ WZÓR FUNKCJI KWADRATOWEJ NA PODSTAWIE JEJ WŁASNOŚCI?","3","youtube",["Wyznaczanie wzoru funkcji kwadratowej na podstawie jej własności"]],
["https://www.youtube.com/embed/-BqskcljHew",["film-podstawa2","film-rozszerzenie2"],"Wyznaczanie wzoru funkcji kwadratowej na podstawie jej własności.","3","youtube",["Wyznaczanie wzoru funkcji kwadratowej na podstawie jej własności"]],
["https://www.youtube.com/embed/tx5RhyT9WUw",["film-podstawa2","film-rozszerzenie2"],"JAK OBLICZYĆ NAJWIĘKSZĄ I NAJMNIEJSZĄ WARTOŚĆ FUNKCJI KWADRATOWEJ","3","youtube",["Najmniejsza oraz największa wartość funkcji kwadratowej w przedziale domkniętym"]],
["https://www.youtube.com/embed/7wUWjLrOoM4",["film-podstawa2","film-rozszerzenie2"],"Wartość najmniejsza i największa funkcji kwadratowej w przedziale domkniętym","3","youtube",["Najmniejsza oraz największa wartość funkcji kwadratowej w przedziale domkniętym"]],
["https://www.youtube.com/embed/Hc77QngKUqg",["film-podstawa2","film-rozszerzenie2"],"JAK ROBIĆ ZADANIA OPTYMALIZACYJNE? - badanie funkcji kwadratowej","3","youtube",["Badanie funkcji kwadratowej - zadania optymalizacyjne", "Zadania prowadzące do równań i nierówności kwadratowych"]],
["https://www.youtube.com/embed/l-L2d6BOWlE",["film-podstawa2","film-rozszerzenie2"],"Optymalizacja - wprowadzenie #1 [ Optymalizacja ]","3","youtube",["Badanie funkcji kwadratowej - zadania optymalizacyjne", "Zadania prowadzące do równań i nierówności kwadratowych"]],
["https://www.youtube.com/embed/3RN2pI--1h8",["film-podstawa2","film-rozszerzenie2"],"Optymalizacja w geometrii #2 [ Optymalizacja ]","3","youtube",["Badanie funkcji kwadratowej - zadania optymalizacyjne", "Zadania prowadzące do równań i nierówności kwadratowych"]],
["https://www.youtube.com/embed/ekLQPaINEtc",["film-podstawa2","film-rozszerzenie2"],"Liceum. Klasa II. Funkcja kwadratowa. Badanie funkcji kwadratowej - zadania optymalizacyjne","3","youtube",["Badanie funkcji kwadratowej - zadania optymalizacyjne", "Zadania prowadzące do równań i nierówności kwadratowych"]],
["https://www.youtube.com/embed/2quidN5TJMk",["film-podstawa2","film-rozszerzenie2"],"Optymalizacja funkcja kwadratowa MATURA PODSTAWA","3","youtube",["Badanie funkcji kwadratowej - zadania optymalizacyjne", "Zadania prowadzące do równań i nierówności kwadratowych"]],
["https://www.youtube.com/embed/P_xzxwzyR8I",["film-podstawa2","film-rozszerzenie2"],"Optymalizacja na maturze","3","youtube",["Badanie funkcji kwadratowej - zadania optymalizacyjne", "Zadania prowadzące do równań i nierówności kwadratowych"]],
["https://www.youtube.com/embed/NjEdRIRzFgM",["film-podstawa2","film-rozszerzenie2"],"Trójmian kwadratowy (zadania optymalizacyjne)","3","youtube",["Badanie funkcji kwadratowej - zadania optymalizacyjne", "Zadania prowadzące do równań i nierówności kwadratowych"]],
["https://www.youtube.com/embed/h7ddgW4fiBs",["film-podstawa2","film-rozszerzenie2"],"RÓWNANIE KWADRATOWE - część 1","3","youtube",["Równania kwadratowe"]],
["https://www.youtube.com/embed/C8rIu7txss4",["film-podstawa2","film-rozszerzenie2"],"Równania kwadratowe - zupełne i niezupełne.","3","youtube",["Równania kwadratowe"]],
["https://www.youtube.com/embed/fH4HSO4RAdk",["film-podstawa2","film-rozszerzenie2"],"Rozwiązywanie równań kwadratowych korzystając z delty #5 [ Równania kwadratowe i postać iloczynowa ]","3","youtube",["Równania kwadratowe"]],
["https://www.youtube.com/embed/4qy-v7s3nck",["film-podstawa2","film-rozszerzenie2"],"Rozwiązywanie różnych równań kwadratowych - zadania #6 [ Równania kwadratowe i postać iloczynowa ]","3","youtube",["Równania kwadratowe"]],
["https://www.youtube.com/embed/XLqsdvYT3NM",["film-podstawa2","film-rozszerzenie2"],"Funkcja kwadratowa - Szybki sposób rozwiązania","3","youtube",["Równania kwadratowe"]],
["https://www.youtube.com/embed/NQb1Q_I0NGE",["film-podstawa2","film-rozszerzenie2"],"MATURA Równania kwadratowe PEWNIAK równania i nierówności cz.3","3","youtube",["Równania kwadratowe"]],
["https://www.youtube.com/embed/7xVD-Eiwg14",["film-podstawa2","film-rozszerzenie2"],"Liceum. Klasa II. Funkcja kwadratowa. Równania prowadzące do równań kwadratowych","3","youtube",["Równania prowadzące do równań kwadratowych"]],
["https://www.youtube.com/embed/eLKR0hl99tM",["film-podstawa2","film-rozszerzenie2"],"Równania prowadzące do równań kwadratowych","3","youtube",["Równania prowadzące do równań kwadratowych"]],
["https://www.youtube.com/embed/fptYYSyi7yI",["film-podstawa2","film-rozszerzenie2"],"Równania prowadzące do równań kwadratowych","3","youtube",["Równania prowadzące do równań kwadratowych"]],
["https://www.youtube.com/embed/IguBfv1jhRY",["film-podstawa2","film-rozszerzenie2"],"Niezbędnik Maturzysty #6 Nierówności kwadratowe","3","youtube",["Równania prowadzące do równań kwadratowych"]],
["https://www.youtube.com/embed/uFWiEc52Xts",["film-podstawa2","film-rozszerzenie2"]," MATURA MATEMATYKA Nierówności kwadratowe PEWNIAK równania i nierówności cz.4","3","youtube",["Równania prowadzące do równań kwadratowych"]],
["https://www.youtube.com/embed/Q-vrMcRevEc",["film-rozszerzenie2"],"Nierówność z niewiadomą pod pierwiastkiem","3","youtube",["Równania i nierówności, w których niewiadoma występuje pod znakiem pierwiastka kwadratowego"]],
["https://www.youtube.com/embed/U10LObnzBbg",["film-rozszerzenie2"],"Równanie z niewiadomą pod pierwiastkiem","3","youtube",["Równania i nierówności, w których niewiadoma występuje pod znakiem pierwiastka kwadratowego"]],
["https://www.youtube.com/embed/KRhcxbWMp4A",["film-rozszerzenie2"],"PROSTE RÓWNANIA Z NIEWIADOMĄ POD PIERWIASTKIEM LEKCJE Z FSOREM #12 ROZSZERZENIE","3","youtube",["Równania i nierówności, w których niewiadoma występuje pod znakiem pierwiastka kwadratowego"]],
["https://www.youtube.com/embed/67mr8qIeXxQ",["film-rozszerzenie2"],"Liceum. Klasa II. Funkcja kwadratowa. Wykres funkcji kwadratowej z wartością bezwzględną","3","youtube",["Wykres funkcji kwadratowej z wartością bezwzględną"]],
["https://www.youtube.com/embed/V9dfy5hH-rk",["film-rozszerzenie2"],"Wykres funkcji kwadratowej z wartością bezwzględną","3","youtube",["Wykres funkcji kwadratowej z wartością bezwzględną"]],
["https://www.youtube.com/embed/w-og0zGOvAE",["film-rozszerzenie2"],"Liceum. Klasa II. Funkcja kwadratowa. Równania kwadratowe z wartością bezwzględną","3","youtube",["Równania i nierówności kwadratowe z wartością bezwzględną"]],
["https://www.youtube.com/embed/KBsG9VSxjs8",["film-rozszerzenie2"]," Równania i nierówności kwadratowe z wartością bezwzględną","3","youtube",["Równania i nierówności kwadratowe z wartością bezwzględną"]],
["https://www.youtube.com/embed/9B5GO5udbYU",["film-rozszerzenie2"],"Reklama wzorów Viete'a","3","youtube",["Wzory Viete'a"]],
["https://www.youtube.com/embed/CknUJcowEQs",["film-rozszerzenie2"],"Liceum. Klasa II. Funkcja kwadratowa. Wzory Vièta","3","youtube",["Wzory Viete'a"]],
["https://www.youtube.com/embed/6Pgk_6UPQjw",["film-rozszerzenie2"],"Liceum. Klasa II. Funkcja kwadratowa. Wzory Vièta","3","youtube",["Wzory Viete'a"]],
["https://www.youtube.com/embed/DeAiyU1QV3o",["film-rozszerzenie2"],"Wzory Viete'y","3","youtube",["Wzory Viete'a"]],
["https://www.youtube.com/embed/LXLNPZn4ybI",["film-rozszerzenie2"],"Funkcja kwadratowa z parametrem, wzory wjeta (Wzory Viete'a), O co w tym chodzi?","3","youtube",["Równania I nierówności kwadratowe z parametrem"]],
["https://www.youtube.com/embed/FwWYXbEfgsA",["film-rozszerzenie2"],"Liceum. Klasa II. Funkcja kwadratowa. Równania i nierówności kwadratowe z parametrem","3","youtube",["Równania I nierówności kwadratowe z parametrem"]],
["https://www.youtube.com/embed/jy8Jlj45cEs",["film-rozszerzenie2"],"Liceum. Klasa II. Funkcja kwadratowa. Równania kwadratowe z wartością bezwzględną i parametrem","3","youtube",["Równania I nierówności kwadratowe z parametrem"]],
["https://www.youtube.com/embed/bLKWrY1acS8",["film-rozszerzenie2"],"Równania kwadratowe z parametrem cz 1","3","youtube",["Równania I nierówności kwadratowe z parametrem"]],
["https://www.youtube.com/embed/t1evq_1tRpA",["film-rozszerzenie2"],"Równania kwadratowe z parametrem cz 2","3","youtube",["Równania I nierówności kwadratowe z parametrem"]],
["https://www.youtube.com/embed/j15XP1fl_Y4",["film-rozszerzenie2"],"Równania kwadratowe z parametrem cz 3","3","youtube",["Równania I nierówności kwadratowe z parametrem"]],
["https://www.youtube.com/embed/GfTASVMYOqQ",["film-rozszerzenie2"],"Równania kwadratowe z parametrem cz 4","3","youtube",["Równania I nierówności kwadratowe z parametrem"]],
["https://www.youtube.com/embed/G6mZ0qzcfjE",["film-rozszerzenie2"],"Równania kwadratowe z parametrem cz 5","3","youtube",["Równania I nierówności kwadratowe z parametrem"]],
["https://www.youtube.com/embed/O7luA3oiHA4",["film-podstawa2","film-rozszerzenie2"],"Liceum. Klasa I. Trójkąty","4","youtube",["Powtórzenie wiadomości z geometrii z klasy 1."]],
["https://www.youtube.com/embed/IxkJHqWCTQI",["film-podstawa2","film-rozszerzenie2"]," Liceum. Klasa I. Wysokości i środkowe w trójkącie","4","youtube",["Powtórzenie wiadomości z geometrii z klasy 1."]],
["https://www.youtube.com/embed/EMkM89YXITk",["film-podstawa2","film-rozszerzenie2"]," Liceum. Klasa I. Przystawanie trójkątów","4","youtube",["Powtórzenie wiadomości z geometrii z klasy 1."]],
["https://www.youtube.com/embed/nEcAi87Oi6A",["film-podstawa2","film-rozszerzenie2"]," Liceum. Klasa I. Podobieństwo trójkątów","4","youtube",["Powtórzenie wiadomości z geometrii z klasy 1."]],
["https://www.youtube.com/embed/30OKS5t1xcc",["film-podstawa2","film-rozszerzenie2"]," Liceum. Klasa I. Twierdzenie Pitagorasa","4","youtube",["Powtórzenie wiadomości z geometrii z klasy 1."]],
["https://www.youtube.com/embed/c7mSym-BW1k",["film-podstawa2","film-rozszerzenie2"]," Liceum. Klasa I. Twierdzenie Talesa","4","youtube",["Powtórzenie wiadomości z geometrii z klasy 1."]],
["https://www.youtube.com/embed/41WFgOhakCA",["film-podstawa2","film-rozszerzenie2"],"styczna do okręgu","4","youtube",["Okrąg. Położenie prostej i okręgu"]],
["https://www.youtube.com/embed/mZ-eXc47YkE",["film-podstawa2","film-rozszerzenie2"],"Liceum. Klasa I. Okręgi i proste","4","youtube",["Okrąg. Położenie prostej i okręgu"]],
["https://www.youtube.com/embed/OYZnw3JNYLE",["film-podstawa2","film-rozszerzenie2"],"Wzajemne położenie prostej i okręgu","4","youtube",["Okrąg. Położenie prostej i okręgu"]],
["https://www.youtube.com/embed/1OsWWgVxAE0",["film-podstawa2","film-rozszerzenie2"],"WZAJEMNE POŁOŻNENIE DWÓCH OKRĘGÓW","4","youtube",["Wzajemne położenie dwóch okręgów"]],
["https://www.youtube.com/embed/yW1xhdUA_3M",["film-podstawa2","film-rozszerzenie2"],"Wzajemne położenie dwóch okręgów","4","youtube",["Wzajemne położenie dwóch okręgów"]],
["https://www.youtube.com/embed/jgz6citS8GE",["film-podstawa2","film-rozszerzenie2"],"Wzajemne położenie okręgów #1 [ Kąty i koła ]","4","youtube",["Wzajemne położenie dwóch okręgów"]],
["https://www.youtube.com/embed/QLzuSRiNTFU",["film-podstawa2","film-rozszerzenie2"],"Kąty w kole - matura poprawkowa 2021 zadanie 19","4","youtube",["Koła i kąty"]],
["https://www.youtube.com/embed/YhCzuHLb-a4",["film-podstawa2","film-rozszerzenie2"],"Zadanie maturalne - kąty w kole","4","youtube",["Koła i kąty"]],
["https://www.youtube.com/embed/c14NaDKbx0E",["film-podstawa2","film-rozszerzenie2"],"Zadanie maturalne - kąty w kole","4","youtube",["Koła i kąty"]],
["https://www.youtube.com/embed/Up21HZnqDOw",["film-podstawa2","film-rozszerzenie2"]," Kąt środkowy i kąt wpisany #2 [ Kąty i koła ]","4","youtube",["Koła i kąty"]],
["https://www.youtube.com/embed/lvf2wwz1CZg",["film-podstawa2","film-rozszerzenie2"]," Kąty wpisane oparte na tym samym łuku #5 [ Kąty i koła ]","4","youtube",["Koła i kąty"]],
["https://www.youtube.com/embed/6dCOoLbw8mc",["film-podstawa2","film-rozszerzenie2"],"Kąty w kole","4","youtube",["Koła i kąty"]],
["https://www.youtube.com/embed/r9rbZR6TXLY",["film-podstawa2","film-rozszerzenie2"],"Liceum. Klasa I. Koło i kąty","4","youtube",["Koła i kąty"]],
["https://www.youtube.com/embed/-f_aoXf1-xk",["film-podstawa2","film-rozszerzenie2"],"Liceum. Klasa I. Twierdzenie o stycznej i siecznej","4","youtube",["Twierdzenie o stycznej i siecznej"]],
["https://www.youtube.com/embed/mRPYsr3-9No",["film-podstawa2","film-rozszerzenie2"],"Twierdzenie o stycznej i siecznej","4","youtube",["Twierdzenie o stycznej i siecznej"]],
["https://www.youtube.com/embed/fpp26ovWXXQ",["film-rozszerzenie2"]," Konstruowanie trójkątów #5 [ Trójkąty - wprowadzenie ]","4","youtube",["Wybrane konstrukcje geometryczne"]],
["https://www.youtube.com/embed/WrWJrKPehjo",["film-rozszerzenie2"]," Jak narysować sześciokąt foremny - Konstrukcja - Matfiz24.pl","4","youtube",["Wybrane konstrukcje geometryczne"]],
["https://www.youtube.com/embed/s-mFUG3Hc9A",["film-rozszerzenie2"]," Liceum. Klasa I. Okrąg opisany na trójkącie |PRZECZYTAJCIE OPIS!|","4","youtube",["Symetralne boków trójkąta. Okrąg opisany na trójkącie"]],
["https://www.youtube.com/embed/qU2rxz-GedM",["film-rozszerzenie2"],"Okrąg opisany na trójkącie","4","youtube",["Symetralne boków trójkąta. Okrąg opisany na trójkącie"]],
["https://www.youtube.com/embed/W-ZzPJfCcZE",["film-rozszerzenie2"],"okrąg opisany na trójkącie","4","youtube",["Symetralne boków trójkąta. Okrąg opisany na trójkącie"]],
["https://www.youtube.com/embed/zWV4jlPidGs",["film-rozszerzenie2"],"okrąg wpisany w trójkąt","4","youtube",["Dwusieczne kątów trójkąta. Okrąg wpisany w trójkąt"]],
["https://www.youtube.com/embed/wkOTQ97lMAc",["film-rozszerzenie2"],"Twierdzenie o dwusiecznej kąta w trójkącie","4","youtube",["Dwusieczne kątów trójkąta. Okrąg wpisany w trójkąt"]],
["https://www.youtube.com/embed/PAQnlTgea7E",["film-rozszerzenie2"],"Liceum. Klasa I. Okrąg wpisany w trójkąt","4","youtube",["Dwusieczne kątów trójkąta. Okrąg wpisany w trójkąt"]],
["https://www.youtube.com/embed/ndc_SnBlNGs",["film-rozszerzenie2"],"okrąg wpisany w trójkąt","4","youtube",["Dwusieczne kątów trójkąta. Okrąg wpisany w trójkąt"]],
["https://www.youtube.com/embed/qX232RNzZ_M",["film-podstawa2","film-rozszerzenie2"],"Trygonometria kąta ostrego - część 1 - podstawy","5","youtube",["Trygonometria kąta ostrego - powtórzenie wiadomości z klasy 1."]],
["https://www.youtube.com/embed/lsmzRf830zE",["film-podstawa2","film-rozszerzenie2"],"Liceum. Klasa I. Wstęp do trygonometrii","5","youtube",["Trygonometria kąta ostrego - powtórzenie wiadomości z klasy 1."]],
["https://www.youtube.com/embed/1LIP7FLpkyM",["film-podstawa2","film-rozszerzenie2"],"Liceum. Klasa I. Funkcje trygonometryczne dowolnego kąta","5","youtube",["Sinus, cosinus, tangens i cotangens dowolnego kąta płaskiego"]],
["https://www.youtube.com/embed/oAXcwemI4b0",["film-podstawa2","film-rozszerzenie2"],"Sinus, cosinus, tangens dowolnego kąta rozwartego #1 [ Funkcje trygonometryczne kąta rozwartego ]","5","youtube",["Sinus, cosinus, tangens i cotangens dowolnego kąta płaskiego"]],
["https://www.youtube.com/embed/dgwkjPUo0HQ",["film-podstawa2","film-rozszerzenie2"],"Funkcje trygonometryczne dowolnego kąta.","5","youtube",["Sinus, cosinus, tangens i cotangens dowolnego kąta płaskiego"]],
["https://www.youtube.com/embed/jdE4Pzj18pM",["film-podstawa2","film-rozszerzenie2"],"Zadanie maturalne - trygonometria - tożsamości.","5","youtube",["Podstawowe tożsamości trygonometryczne"]],
["https://www.youtube.com/embed/1UbiaUF6jEM",["film-podstawa2","film-rozszerzenie2"],"Liceum. Klasa I. Tożsamości trygonometryczne","5","youtube",["Podstawowe tożsamości trygonometryczne"]],
["https://www.youtube.com/embed/uzOmcLMuQLc",["film-podstawa2","film-rozszerzenie2"],"Trygonometria - zadanie z tożsamości trygonometrycznych - Oblicz tangens konta alfa - rozwiązanie","5","youtube",["Podstawowe tożsamości trygonometryczne"]],
["https://www.youtube.com/embed/N-SFtVnHlLc",["film-podstawa2","film-rozszerzenie2"],"Jedynka trygonometryczna #1 [ Tożsamości trygonometryczne ]","5","youtube",["Podstawowe tożsamości trygonometryczne"]],
["https://www.youtube.com/embed/tfarfJ2bbV0",["film-podstawa2","film-rozszerzenie2"],"Tangens kąta #2 [ Tożsamości trygonometryczne ]","5","youtube",["Podstawowe tożsamości trygonometryczne"]],
["https://www.youtube.com/embed/8LDAjXNJ8kg",["film-podstawa2","film-rozszerzenie2"],"Funkcje trygonometryczne kąta ostrego #3 [ Tożsamości trygonometryczne ]","5","youtube",["Podstawowe tożsamości trygonometryczne"]],
["https://www.youtube.com/embed/pwoZmLY2ITU",["film-podstawa2","film-rozszerzenie2"],"Wzory redukcyjne.","5","youtube",["Wybrane wzory redukcyjne"]],
["https://www.youtube.com/embed/kD4ZJ12ZsxI",["film-podstawa2","film-rozszerzenie2"],"Liceum. Klasa I. Wzory redukcyjne","5","youtube",["Wybrane wzory redukcyjne"]],
["https://www.youtube.com/embed/1h1AATqXkaQ",["film-podstawa2","film-rozszerzenie2"],"Korzystanie z wybranych wzorów redukcyjnych #2 [ Funkcje trygonometryczne kąta rozwartego ]","5","youtube",["Wybrane wzory redukcyjne"]],
["https://www.youtube.com/embed/7p21166FOok",["film-rozszerzenie2"]," Matematyka - Miara łukowa kąta (część pierwsza)","5","youtube",["Kąt skierowany. Miara łukowa kąta"]],
["https://www.youtube.com/embed/4mRC2u3cWbU",["film-rozszerzenie2"]," Matematyka - Miara łukowa kąta (część druga)","5","youtube",["Kąt skierowany. Miara łukowa kąta"]],
["https://www.youtube.com/embed/G-9fyr_FPNQ",["film-rozszerzenie2"],"Kąt skierowany","5","youtube",["Kąt skierowany. Miara łukowa kąta"]],
["https://www.youtube.com/embed/WXuqrF5ftSM",["film-rozszerzenie2"],"Miara łukowa kąta","5","youtube",["Kąt skierowany. Miara łukowa kąta"]],
["https://www.youtube.com/embed/Ma_nhh1GQKU",["film-rozszerzenie2"]," Wprowadzenie do miary łukowej - radiany","5","youtube",["Kąt skierowany. Miara łukowa kąta"]],
["https://www.youtube.com/embed/cOVoAkAWdpY",["film-rozszerzenie2"],"Trygonometria - wyznaczanie okresu funkcji trygonometrycznych","5","youtube",["Funkcje trygonometryczne zmiennej rzeczywistej"]],
["https://www.youtube.com/embed/Irh1S9cZLQU",["film-rozszerzenie2"],"Zbadaj parzystość / nieparzystość funkcji cz. 1","5","youtube",["Funkcje trygonometryczne zmiennej rzeczywistej"]],
["https://www.youtube.com/embed/rzACuSgpZPA",["film-rozszerzenie2"],"Zbadaj parzystość / nieparzystość funkcji cz. 2","5","youtube",["Funkcje trygonometryczne zmiennej rzeczywistej"]],
["https://www.youtube.com/embed/th099zUOJ90",["film-rozszerzenie2"],"Wykresy funkcji trygonometrycznych i okresowość","5","youtube",["Wykresy funkcji trygonometrycznych"]],
["https://www.youtube.com/embed/loITLluuWG8",["film-rozszerzenie2"],"Wykresy funkcji trygonometrycznych","5","youtube",["Wykresy funkcji trygonometrycznych"]],
["https://www.youtube.com/embed/j3aAEgZvUkQ",["film-rozszerzenie2"],"Dziedzina, zbiór wartości i wykres funkcji sinus","5","youtube",["Wykresy funkcji trygonometrycznych"]],
["https://www.youtube.com/embed/-KZsMNL6pS4",["film-rozszerzenie2"],"Wykres funkcji cosinus","5","youtube",["Wykresy funkcji trygonometrycznych"]],
["https://www.youtube.com/embed/t89s-H-QHeA",["film-podstawa2","film-rozszerzenie2"],"Długość odcinka- geometria analityczna.", "6", "youtube",["Odcinek w układzie współrzędnych"]],
["https://www.youtube.com/embed/WLEJMrGIfsg",["film-podstawa2","film-rozszerzenie2"],"Wektor w układzie współrzędnych -definicje, przykłady", "6", "youtube",["Odcinek w układzie współrzędnych"]],
["https://www.youtube.com/embed/LKZiXAKia7g",["film-podstawa2","film-rozszerzenie2"],"Środek odcinka- geometria analityczna.", "6", "youtube",["Odcinek w układzie współrzędnych"]],
["https://www.youtube.com/embed/bloPPXEDUK4",["film-podstawa2","film-rozszerzenie2"],"Geometria Analityczna wprowadzenie + zadania", "6", "youtube",["Odcinek w układzie współrzędnych"]],
["https://www.youtube.com/embed/10OPCP4SnY8",["film-podstawa2","film-rozszerzenie2"],"Równanie kierunkowe prostej.","6","youtube",["Równanie kierunkowe prostej"]],
["https://www.youtube.com/embed/ZeGevXIOVDo",["film-podstawa2","film-rozszerzenie2"],"Równanie ogólne prostej.","6","youtube",["Równanie ogólne prostej"]],
["https://www.youtube.com/embed/fyjUJ758tA0",["film-podstawa2","film-rozszerzenie2"],"Równanie prostej w postaci ogólnej","6","youtube",["Równanie ogólne prostej"]],
["https://www.youtube.com/embed/_q3yeKjr_uI",["film-podstawa2","film-rozszerzenie2"],"Równanie okręgu","6","youtube",["Równanie okręgu"]],
["https://www.youtube.com/embed/1A--OvBIq8s",["film-podstawa2","film-rozszerzenie2"],"Równanie okręgu","6","youtube",["Równanie okręgu"]],
["https://www.youtube.com/embed/lsdkLaMoFBo",["film-podstawa2","film-rozszerzenie2"],"Równanie okręgu w pigułce - jak wygląda w zadaniach, rodzaje równania, na co uważać","6","youtube",["Równanie okręgu"]],
["https://www.youtube.com/embed/NMvofh7ciTo",["film-podstawa2","film-rozszerzenie2"],"Wyznacz punkty przecięcia paraboli i prostej","6","youtube",["Wyznaczanie w układzie współrzędnych punktów wspólnych prostych, okręgów i parabol"]],
["https://www.youtube.com/embed/rZB4MLW_Udo",["film-podstawa2","film-rozszerzenie2"],"PROSTA PRZECINA OKRĄG - WYZNACZ PUNKTY","6","youtube",["Wyznaczanie w układzie współrzędnych punktów wspólnych prostych, okręgów i parabol"]],
["https://www.youtube.com/embed/bo08Pyt-DGU",["film-podstawa2","film-rozszerzenie2"],"Wyznacz punkty wspólne prostej i paraboli","6","youtube",["Wyznaczanie w układzie współrzędnych punktów wspólnych prostych, okręgów i parabol"]],
["https://www.youtube.com/embed/R69V3vmNxS8",["film-podstawa2","film-rozszerzenie2"],"Wszystko co musisz wiedzieć o geometrii analitycznej KURS MATURA PODSTAWOWA cz.1","6","youtube",["Zastosowanie układów równań do rozwiązywania zadań z geometrii analitycznej"]],
["https://www.youtube.com/embed/Ig47g8-3X0M",["film-podstawa2","film-rozszerzenie2"],"Wszystko co musisz wiedzieć o geometrii analitycznej KURS MATURA PODSTAWOWA cz.2","6","youtube",["Zastosowanie układów równań do rozwiązywania zadań z geometrii analitycznej"]],
["https://www.youtube.com/embed/Om1KCOJ4Ais",["film-podstawa2","film-rozszerzenie2"],"Geometria analityczna 4 zadania","6","youtube",["Zastosowanie układów równań do rozwiązywania zadań z geometrii analitycznej"]],
["https://www.youtube.com/embed/11TaEb4Sctc",["film-podstawa2","film-rozszerzenie2"],"Geometria analityczna - zadania z matury podstawowej","6","youtube",["Zastosowanie układów równań do rozwiązywania zadań z geometrii analitycznej"]],
];

export function shuffle(array) {
  let currentIndex = array.length,
    randomIndex:number;
  while (currentIndex > 0) {
    randomIndex = Math.floor(Math.random() * currentIndex);
    currentIndex--;
    [array[currentIndex], array[randomIndex]] = [
      array[randomIndex],
      array[currentIndex],
    ];
  }
  return array;
}
filmyYtLinki = shuffle(filmyYtLinki);
export default filmyYtLinki;
