const tematy = {
  1: {
    podstawa: {},
    rozszerzenie: {},
  },
  2: {
    podstawa: {
      1: {
        1: "Zbiór. Działania na zbiorach",
        2: "Zbiory liczbowe. Oś liczbowa",
        3: "Prawa działania w zbiorze liczb rzeczywistych",
        4: "Przedziały",
        5: "Zbiór liczb naturalnych i zbiór liczb całkowitych",
        6: "Przypomnienie i uzupełnienie wiadomości o równaniach",
        7: "Rozwiązywanie równań metodą równań równoważnych",
        8: "Nierówność z jedną niewiadomą. Rozwiązywanie nierówności metodą nierówności równoważnych",
        9: "Procenty",
        10: "Punkty procentowe",
      },
      2: {
        1: "Potęga o wykładniku naturalnym",
        2: "Pierwiastek arytmetyczny. Pierwiastek stopnia nieparzystego z liczby ujemnej",
        3: "Działania na wyrażeniach algebraicznych",
        4: "Wzory skróconego mnożenia stopnia 2",
        5: "Potęga o wykładniku całkowitym ujemnym",
        6: "Potęga o wykładniku wymiernym",
        7: "Potęga o wykładniku rzeczywistym",
        8: "Określenie logarytmu",
        9: "Zastosowanie logarytmów",
        10: "Zdanie. Zaprzeczenie zdania",
        11: "Zdania złożone. Zaprzeczenia zdań złożonych. Definicja. Twierdzenie. Dowód twierdzenia",
        12: "Przekształcanie wzorów",
        13: "Średnie",
      },
      3: {
        1: "Pojęcie funkcji. Funkcja liczbowa. Sposoby opisywania funkcji",
        2: "Wykres funkcji",
        3: "Dziedzina funkcji liczbowej",
        4: "Zbiór wartości funkcji liczbowej. Najmniejsza i największa wartość funkcji.",
        5: "Miejsce zerowe funkcji",
        6: "Monotoniczność funkcji",
        7: "Funkcje różnowartościowe",
        8: "Odczytywanie wartości funkcji na podstawie jej wykresu",
        9: "Zastosowanie wiadomości o funkcjach do opisywania, interpretowania i przetwarzania informacji wyrażonych w postaci wykresu funkcji",
      },
      4: {
        1: "Proporcjonalność prosta",
        2: "Funkcja liniowa. Wykres i miejsce zerowe funkcji liniowej",
        3: "Znaczenie współczynnika kierunkowego w wykresie funkcji liniowej",
        4: "Właściwości funkcji liniowej - różne zadania",
      },
      5: {
        1: "Równania pierwszego stopnia z dwiema niewiadomymi",
        2: "Układy równań pierwszego stopnia z dwiema niewiadomymi",
        3: "Graficzne rozwiązywanie układów równań",
        4: "Rozwiązywanie układów równań pierwszego stopnia z dwiema niewiadomymi metodą podstawiania",
        5: "Rozwiązywanie układów równań pierwszego stopnia z dwiema niewiadomymi metodą przeciwnych współczynników",
        6: "Zastosowanie układów równań do rozwiązywania zadań",
      },
      6: {
        1: "Funkcja kwadratowa",
        2: "Funkcja kwadratowa - zastosowania",
        3: "Proporcjonalność odwrotna",
        4: "Funkcja wykładnicza",
        5: "Funkcja logarytmiczna",
      },
      7: {
        1: "Punkt, prosta, odcinek, półprosta, kąt, figura wypukła, figura ograniczona",
        2: "Wzajemne położenie prostych na płaszczyźnie, odległość punktu od prostej, odległość między prostymi równoległymi, symetralna odcinka, dwusieczna kąta",
        3: "Dwie proste przecięte trzecią prostą, suma kątów w trójkącie, wielokąt, wielokąt foremny, suma kątów w wielokącie",
        4: "Twierdzenie Talesa",
        5: "Podział trójkątów, nierówność trójkąta, odcinek łączący środki boków w trójkącie",
        6: "Twierdzenie Pitagorasa, Twierdzenie odwrotne do twierdzenia Pitagorasa",
        7: "Wysokości w trójkącie, środkowe w trójkącie",
        8: "Przystawanie trójkątów",
        9: "Podobieństwo trójkątów",
        10: "Podobieństwo trójkątów - zastosowanie w zadaniach",
      },
      8: {
        1: "Określenie sinusa, cosinusa, tangensa i cotangensa w trójkącie prostokątnym",
        2: "Wartości sinusa, cosinusa, tangensa i cotangensa kątów 30°, 45° i 60°",
        3: "Zależności między funkcjami trygonometrycznymi tego samego kąta ostrego",
      },
    },
    rozszerzenie: {},
  },
  3: {
    podstawa: {},
    rozszerzenie: {},
  },
  4: {
    podstawa: {},
    rozszerzenie: {},
  },
};
export default tematy;
