const filmyYtLinki = [
  [
    "https://www.youtube.com/embed/naq9D6jvnhA",
    ["film-podstawa2", "film-rozszerzenie2"],
    "Matematyka - Wielomiany jednej zmiennej (część I)",
    "8",
    "youtube",
  ],
  [
    "https://www.youtube.com/embed/ev_-R-3W_yo",
    ["film-podstawa2", "film-rozszerzenie2"],
    "Co to jest wielomian? #1 [ Wielomiany ]",
    "8",
    "youtube",
  ],
  [
    "https://www.youtube.com/embed/V2D8wYNpAk8",
    ["film-podstawa2", "film-rozszerzenie2"],
    "Dodawanie i odejmowanie wielomianów",
    "8",
    "youtube",
  ],
  [
    "https://www.youtube.com/embed/VZA09ymFcV4",
    ["film-podstawa2", "film-rozszerzenie2"],
    "Szybko i na temat. Dzielenie Wielomianów Krok po Kroku",
    "8",
    "youtube",
  ],
  [
    "https://www.youtube.com/embed/77CgfPFONWE",
    ["film-podstawa2", "film-rozszerzenie2"],
    "Sprawdzian na 5!WIELOMIANY (rozkład na czynniki, dzielenie, Horner, równania, TW o reszcie/Bézouta)",
    "8",
    "youtube",
  ],
  [
    "https://www.youtube.com/embed/KLjji_I3XvA",
    ["film-podstawa2", "film-rozszerzenie2"],
    "Liceum. Klasa II. Wielomiany. Nierówności wielomianowe",
    "8",
    "youtube",
  ],
  [
    "https://www.youtube.com/embed/vQgrdSAjYaE",
    ["film-podstawa2", "film-rozszerzenie2"],
    "Dodawanie, odejmowanie i mnożenie wielomianów #3 [ Wielomiany ]",
    "8",
    "youtube",
  ],
  [
    "https://www.youtube.com/embed/f_Kv7-oiMLw",
    ["film-podstawa2", "film-rozszerzenie2"],
    "WSZYSTKO o: NIERÓWNOŚCI WIELOMIANOWE. Jak rysować wykres wielomianu?Co to jest krotność pierwiastka?",
    "8",
    "youtube",
  ],
  [
    "https://www.youtube.com/embed/5UaDP_fF8hY",
    ["film-rozszerzenie2"],
    "Wielomiany co trzeba ogarniać? Matura Matematyka Rozszerzenie",
    "8",
    "youtube",
  ],
  [
    "https://www.youtube.com/embed/eQTEXfqLQYE",
    ["film-podstawa2", "film-rozszerzenie2"],
    "Wzory skróconego mnożenia - sześcian sumy i różnicy.",
    "8",
    "youtube",
  ],
  [
    "https://www.youtube.com/embed/ehRXj3GEpIw",
    ["film-rozszerzenie2"],
    "Matura rozszerzona - kurs - wzory skróconego mnożenia",
    "8",
    "youtube",
  ],
  [
    "https://www.youtube.com/embed/Q-lkLAeKtlA",
    ["film-podstawa2", "film-rozszerzenie2"],
    "Jak dzielić (pisemnie) WIELOMIAN przez DWUMIAN na MATURZE PODSTAWOWEJ?",
    "8",
    "youtube",
  ],
  [
    "https://www.youtube.com/embed/9piOqP5jcw4",
    ["film-podstawa2", "film-rozszerzenie2"],
    "Dzielenie wielomianów #4 [ Wielomiany ]",
    "8",
    "youtube",
  ],
  [
    "https://www.youtube.com/embed/msfZ8_eHIoM",
    ["film-podstawa2", "film-rozszerzenie2"],
    "Pierwiastki całkowite oraz wymierne wielomianu #8 [ Wielomiany ]",
    "8",
    "youtube",
  ],
  [
    "https://www.youtube.com/embed/5ywgT7USp4Y",
    ["film-rozszerzenie2"],
    "Wielomiany na poziomie rozszerzonym",
    "8",
    "youtube",
  ],
  [
    "https://www.youtube.com/embed/KPOFrG8HOwo",
    ["film-podstawa2", "film-rozszerzenie2"],
    "WEKTOR w układzie współrzędnych",
    "1",
    "youtube",
  ],
  [
    "https://www.youtube.com/embed/LqBrQp-f2I0",
    ["film-podstawa2", "film-rozszerzenie2"],
    "Wektory - Wprowadzenie Odc.1 (na szybko bo wychodzę za 5 min)",
    "1",
    "youtube",
  ],
  [
    "https://www.youtube.com/embed/WCOChZ-BaCM",
    ["film-rozszerzenie2"],
    "Wektory - wprowadzenie - najważniejsze informacje",
    "1",
    "youtube",
  ],
  [
    "https://www.youtube.com/embed/9agT9Lu6pJQ",
    ["film-podstawa2", "film-rozszerzenie2"],
    "Liceum. Klasa I. Wektor w układzie współrzędnych",
    "1",
    "youtube",
  ],
  [
    "https://www.youtube.com/embed/C3RlRjnBE0c",
    ["film-podstawa2", "film-rozszerzenie2"],
    "Przesuwanie wykresów funkcji wzdłuż osi X i Y oraz o wektor",
    "1",
    "youtube",
  ],

  [
    "https://www.youtube.com/embed/sD4mC5Ux6pM",
    ["film-podstawa2", "film-rozszerzenie2"],
    "Przesuwanie wykresu funkcji wzdłuż osi OX i OY",
    "1",
    "youtube",
  ],

  [
    "https://www.youtube.com/embed/7xxIkATsBeo",
    ["film-podstawa2", "film-rozszerzenie2"],
    "Przesunięcie wykresu funkcji wzdłuż osi układu współrzędnych cz.2 MATEMATYKA LEKCJE Z FSORE",
    "1",
    "youtube",
  ],

  [
    "https://www.youtube.com/embed/nxuZvjTxMOk",
    ["film-podstawa2", "film-rozszerzenie2"],
    "Matematyka - Przesunięcie funkcji wzdłuż osi OX",
    "1",
    "youtube",
  ],

  [
    "https://www.youtube.com/embed/WMVe1NZBrsE",
    ["film-podstawa2", "film-rozszerzenie2"],
    "Przesuwanie funkcji w górę, w dół, w prawo, w lewo | MatFiz24.PL",
    "1",
    "youtube",
  ],
  [
    "https://www.youtube.com/embed/yLRIkacEAy0",
    ["film-podstawa2", "film-rozszerzenie2"],
    "Przekształcanie wykresu funkcji - symetria względem osi OX i OY",
    "1",
    "youtube",
  ],
  [
    "https://www.youtube.com/embed/Q-0ylc-dqn8",
    ["film-podstawa2", "film-rozszerzenie2"],
    "Symetria osiowa względem osi OX i OY - definicje, przykłady",
    "1",
    "youtube",
  ],
  [
    "https://www.youtube.com/embed/m48o2yHJoDA",
    ["film-podstawa2", "film-rozszerzenie2"],
    "Symetria osiowa w układzie współrzędnych #3 [ Symetria ]",
    "1",
    "youtube",
  ],
  [
    "https://www.youtube.com/embed/H9i1y9Hdtl4",
    ["film-podstawa2", "film-rozszerzenie2"],
    "Liceum. Klasa I. Symetria środkowa i osiowa w układzie współrzędnych",
    "1",
    "youtube",
  ],
  [
    "https://www.youtube.com/embed/dPZVFCuQCvI",
    ["film-podstawa2", "film-rozszerzenie2"],
    "Symetria środkowa. Symetria środkowa względem punktu (0,0) - definicje, przykłady",
    "1",
    "youtube",
  ],
  [
    "https://www.youtube.com/embed/qCqHk3kFGZo",
    ["film-podstawa2", "film-rozszerzenie2"],
    "Symetria środkowa względem punktu 0(0,0)",
    "1",
    "youtube",
  ],
  [
    "https://www.youtube.com/embed/4S0vLLSkcBs",
    ["film-podstawa2", "film-rozszerzenie2"],
    "Symetria środkowa w układzie współrzędnych #6 [ Symetria ]",
    "1",
    "youtube",
  ],
];
export default filmyYtLinki;
